<%@ include file="/WEB-INF/jsp/common/include.jsp" %>


<w:ifUserCanPerformAction action="editInvitation" var="canEdit"></w:ifUserCanPerformAction>

<script language="JavaScript">
  function onPageLoad(){
    <c:if test="${form.reportUrl != null}">
      openNewWindow('<c:out value="${form.reportUrl}" escapeXml="false" />');
    </c:if>
  }
</script>

<div class="yui-navset"> 
  <ul class="yui-nav"> 
    <li><a href="<html:rewrite action="farm300"/>?pin=<c:out value="${account.client.participantPin}"/>&year=<c:out value="${account.programYear}"/>"><em><fmt:message key="Status"/></em></a></li> 
    <li><a href="<html:rewrite action="farm340"/>"><em><fmt:message key="Authorized.Users"/></em></a></li> 
    <li class="selected"><a href="<html:rewrite action="farm330"/>"><em><fmt:message key="Invitations"/></em></a></li> 
    <w:ifUserCanPerformAction action="viewReasonabilityTests">
      <li><a href="<html:rewrite action="farm350"/>"><em><fmt:message key="Reasonability.Tests"/></em></a></li> 
    </w:ifUserCanPerformAction>
  </ul> 
  
  <div class="yui-content"> 
    <table class="searchresults"> 
      <tr> 
        <th><fmt:message key="Generated.Date"/></th> 
        <th><fmt:message key="Generated.By"/></th>
        <th><fmt:message key="Activated.Date"/></th> 
        <th><fmt:message key="Activated.By"/></th> 
        <th><fmt:message key="Status"/></th> 
        <th><fmt:message key="Details"/></th>
      </tr> 
      
      <c:forEach var="subscription" varStatus="loop" items="${account.client.clientSubscription}">
        <tr> 
          <td><fmt:formatDate pattern="yyyy-MM-dd" value="${subscription.generatedDate}" /></td> 
          <td><c:out value="${subscription.generatedByUserid}"/></td> 
          <td><fmt:formatDate pattern="yyyy-MM-dd" value="${subscription.activatedDate}" /></td> 
          <td><c:out value="${subscription.activatedByUserid}"/></td> 
          
          <c:choose>
            <c:when test="${canEdit && subscription.subscriptionStatusCode == 'GEN'}">
               <td class="button">
                 <a id="<u:id prefix="button" var="buttons"/>" 
                    href="javascript:invalidate('<c:out value="${subscription.clientSubscriptionId}"/>', '<c:out value="${subscription.revisionCount}"/>');">
                   Invalidate
                 </a>
               </td>
            </c:when>
            <c:otherwise>
              <td><c:out value="${subscription.subscriptionStatusCodeDescription}"/></td>
            </c:otherwise>
          </c:choose>
          
          <td class="button"><a id="<u:id prefix="button" var="buttons"/>" href="javascript:showInvitationDetailPanel('<c:out value="${loop.index}"/>')"><fmt:message key="Details"/></a></td> 
        </tr> 
      </c:forEach>
      
    </table> 
    <p></p> 
    
    <c:if test="${canEdit}">
      <a id="generateSubscriptionLetterButton" href="javascript:generateLetter();"><fmt:message key="Generate.Invitation.Letter"/></a> 
    </c:if>
  </div>
</div>




<c:if test="${canEdit}">
  <script type="text/javascript"> 
      function invalidate(clientSubscriptionId, revisionCount) {
        if( confirm("Do you really want to invalidate this invitation?") ) {
          showProcessing();
          document.location.href = "invalidateSubscription.do?clientSubscriptionId=" + clientSubscriptionId + "&revisionCount=" + revisionCount;
        }
      }

      function generateLetter() {
        showProcessing();
        document.location.href = "generateSubscription.do";
      }
  </script> 
</c:if>


<div id="panel"></div>

<script type="text/javascript">
  <c:if test="${canEdit}">
    new YAHOO.widget.Button("generateSubscriptionLetterButton");
  </c:if>
  
  <c:forEach var="item" items="${buttons}">
    new YAHOO.widget.Button("<c:out value="${item}"/>");
  </c:forEach>
  
  var panelBodies = new Array();
  
  <c:forEach var="subscription" varStatus="loop" items="${account.client.clientSubscription}">
    panelBodies.push("<table class=\"details\"> \
      <tr> \
        <th>Generated Date:</th> \
        <td><fmt:formatDate pattern="yyyy-MM-dd" value="${subscription.generatedDate}" /></td> \
      </tr> \
      <tr> \
        <th>Generated By:</th> \
        <td><c:out value="${subscription.javascriptGeneratedByUserid}"/></td> \
      </tr> \
      <tr> \
        <th>Activated Date:</th> \
        <td><fmt:formatDate pattern="yyyy-MM-dd" value="${subscription.activatedDate}" /></td> \
      </tr> \
      <tr> \
        <th>Activated By:</th> \
        <td><c:out value="${subscription.javascriptActivatedByUserid}"/></td> \
      </tr> \
      <tr> \
        <th>Status:</th> \
        <td><c:out value="${subscription.subscriptionStatusCodeDescription}"/></td> \
      </tr> \
      <tr> \
        <th>Subscription Code:</th> \
        <td><c:out value="${subscription.subscriptionNumber}"/></td> \
      </tr> \
    </table>");
  </c:forEach>
  
  function showInvitationDetailPanel(index) { 
    var panel = new YAHOO.widget.Panel("panel", {
      width:"400px",
      constraintoviewport: true, 
      underlay:"shadow", 
      close:true, 
      visible:false, 
      draggable:true,
      dragOnly:true});
  
    panel.setHeader("Details");
    panel.setBody(panelBodies[index]);
    panel.render("bcgov-content-liner");
    panel.show();
    panel.center();
  }
  
</script> 

