create or replace procedure farms_write_pkg.write_claim(
    inout io_agristability_claim_id farms.farm_agristability_claims.agristability_claim_id%type,
    inout io_revision_count farms.farm_agristability_claims.revision_count%type,
    in in_administrative_cost_share farms.farm_agristability_claims.administrative_cost_share%type,
    in in_late_application_penalty farms.farm_agristability_claims.late_application_penalty%type,
    in in_maximum_contribution farms.farm_agristability_claims.maximum_contribution%type,
    in in_outstanding_fees farms.farm_agristability_claims.outstanding_fees%type,
    in in_program_year_margin farms.farm_agristability_claims.program_year_margin%type,
    in in_prod_insur_deemed_benefit farms.farm_agristability_claims.prod_insur_deemed_benefit%type,
    in in_pi_deemed_bnft_manual_calc_ind farms.farm_agristability_claims.pi_deemed_bnft_manual_calc_ind%type,
    in in_program_year_payments_rec farms.farm_agristability_claims.program_year_payments_received%type,
    in in_allocated_reference_margin farms.farm_agristability_claims.allocated_reference_margin%type,
    in in_repayment_of_cash_advances farms.farm_agristability_claims.repayment_of_cash_advances%type,
    in in_total_payment farms.farm_agristability_claims.total_payment%type,
    in in_supply_managed_comm_adj farms.farm_agristability_claims.supply_managed_commodities_adj%type,
    in in_producer_share farms.farm_agristability_claims.producer_share%type,
    in in_federal_contributions farms.farm_agristability_claims.federal_contributions%type,
    in in_provincial_contributions farms.farm_agristability_claims.provincial_contributions%type,
    in in_interim_contributions farms.farm_agristability_claims.interim_contributions%type,
    in in_whole_farm_allocation farms.farm_agristability_claims.whole_farm_allocation%type,
    in in_tier2_trigger farms.farm_agristability_claims.tier2_trigger%type,
    in in_tier2_margin_decline farms.farm_agristability_claims.tier2_margin_decline%type,
    in in_tier2_benefit farms.farm_agristability_claims.tier2_benefit%type,
    in in_tier3_trigger farms.farm_agristability_claims.tier3_trigger%type,
    in in_tier3_margin_decline farms.farm_agristability_claims.tier3_margin_decline%type,
    in in_tier3_benefit farms.farm_agristability_claims.tier3_benefit%type,
    in in_margin_decline farms.farm_agristability_claims.margin_decline%type,
    in in_negative_margin_decline farms.farm_agristability_claims.negative_margin_decline%type,
    in in_negative_margin_benefit farms.farm_agristability_claims.negative_margin_benefit%type,
    in in_total_benefit farms.farm_agristability_claims.total_benefit%type,
    in in_adjusted_reference_margin farms.farm_agristability_claims.adjusted_reference_margin%type,
    in in_unadjusted_reference_margin farms.farm_agristability_claims.unadjusted_reference_margin%type,
    in in_reference_margin_limit farms.farm_agristability_claims.reference_margin_limit%type,
    in in_reference_margin_limit_cap farms.farm_agristability_claims.reference_margin_limit_cap%type,
    in in_ref_marg_lim_for_bnft_calc farms.farm_agristability_claims.ref_marg_limit_for_bnft_calc%type,
    in in_benefit_before_deductions farms.farm_agristability_claims.benefit_before_deductions%type,
    in in_benefit_after_pi_ded farms.farm_agristability_claims.benefit_after_prod_insur_ded%type,
    in in_applied_benefit_percent farms.farm_agristability_claims.applied_benefit_percent%type,
    in in_benefit_after_appl_ben_pct farms.farm_agristability_claims.benefit_after_appl_benefit_pct%type,
    in in_interim_benefit_percent farms.farm_agristability_claims.interim_benefit_percent%type,
    in in_benefit_after_interim_ded farms.farm_agristability_claims.benefit_after_interim_ded%type,
    in in_payment_cap farms.farm_agristability_claims.payment_cap%type,
    in in_benefit_after_payment_cap farms.farm_agristability_claims.benefit_after_payment_cap%type,
    in in_late_enrolment_penalty farms.farm_agristability_claims.late_enrolment_penalty%type,
    in in_bnft_after_late_enrol_penal farms.farm_agristability_claims.bnft_after_late_enrol_penalty%type,
    in in_late_enr_pen_af_apl_ben_pct farms.farm_agristability_claims.late_enr_pnlty_aft_apl_ben_pct%type,
    in in_standard_benefit farms.farm_agristability_claims.standard_benefit%type,
    in in_enh_ref_margin_for_ben_calc farms.farm_agristability_claims.enh_ref_margin_for_beneft_calc%type,
    in in_enh_margin_decline farms.farm_agristability_claims.enh_margin_decline%type,
    in in_enh_positive_margin_decline farms.farm_agristability_claims.enh_positive_margin_decline%type,
    in in_enh_positive_margin_benefit farms.farm_agristability_claims.enh_positive_margin_benefit%type,
    in in_enh_negative_margin_decline farms.farm_agristability_claims.enh_negative_margin_decline%type,
    in in_enh_negative_margin_benefit farms.farm_agristability_claims.enh_negative_margin_benefit%type,
    in in_enh_benefit_before_ded farms.farm_agristability_claims.enh_benefit_before_deductions%type,
    in in_enh_benefit_aft_prodins_ded farms.farm_agristability_claims.enh_benefit_after_prodins_ded%type,
    in in_enh_benefit_aft_interim_ded farms.farm_agristability_claims.enh_benefit_after_interim_ded%type,
    in in_enh_benefit_after_payment_cap farms.farm_agristability_claims.enh_benefit_after_payment_cap%type,
    in in_enh_total_benefit farms.farm_agristability_claims.enh_total_benefit%type,
    in in_enh_additional_benefit farms.farm_agristability_claims.enh_additional_benefit%type,
    in in_enh_late_enrolment_penalty farms.farm_agristability_claims.enh_late_enrolment_penalty%type,
    in in_enh_bnft_aftr_late_enr_penalty farms.farm_agristability_claims.enh_bnft_aftr_late_enr_penalty%type,
    in in_enh_bnft_aftr_applied_bnft_pct farms.farm_agristability_claims.enh_bnft_aftr_applied_bnft_pct%type,
    in in_enh_lat_en_pnlty_af_apl_bn_pct farms.farm_agristability_claims.enh_lat_en_pnlty_af_apl_bn_pct%type,
    in in_ratio_adj_reference_margin farms.farm_agristability_claims.ratio_adj_reference_margin%type,
    in in_additive_adj_reference_marg farms.farm_agristability_claims.additive_adj_reference_margin%type,
    in in_agristability_scenario_id farms.farm_agristability_claims.agristability_scenario_id%type,
    in in_structural_change_code farms.farm_agristability_claims.structural_change_code%type,
    in in_expense_structural_chg_code farms.farm_agristability_claims.expense_structural_change_code%type,
    in in_user_id farms.farm_agristability_claims.who_updated%type
)
language plpgsql
as
$$
declare

    -- used during insert
    v_rows_affected  bigint := null;
    v_revision_count farms.farm_agristability_claims.revision_count%type := null;

begin
    if coalesce(io_agristability_claim_id::text, '') = '' then
        --
        -- insert
        --
        insert into farms.farm_agristability_claims (
            agristability_claim_id,
            administrative_cost_share,
            late_application_penalty,
            maximum_contribution,
            outstanding_fees,
            program_year_margin,
            prod_insur_deemed_benefit,
            pi_deemed_bnft_manual_calc_ind,
            program_year_payments_received,
            allocated_reference_margin,
            repayment_of_cash_advances,
            total_payment,
            supply_managed_commodities_adj,
            producer_share,
            federal_contributions,
            provincial_contributions,
            interim_contributions,
            whole_farm_allocation,
            tier2_margin_decline,
            tier3_margin_decline,
            tier2_benefit,
            tier3_benefit,
            margin_decline,
            negative_margin_decline,
            negative_margin_benefit,
            total_benefit,
            adjusted_reference_margin,
            unadjusted_reference_margin,
            reference_margin_limit,
            reference_margin_limit_cap,
            ref_marg_limit_for_bnft_calc,
            tier2_trigger,
            tier3_trigger,
            benefit_before_deductions,
            benefit_after_prod_insur_ded,
            applied_benefit_percent,
            benefit_after_appl_benefit_pct,
            interim_benefit_percent,
            benefit_after_interim_ded,
            payment_cap,
            benefit_after_payment_cap,
            late_enrolment_penalty,
            bnft_after_late_enrol_penalty,
            late_enr_pnlty_aft_apl_ben_pct,
            standard_benefit,
            enh_ref_margin_for_beneft_calc,
            enh_margin_decline,
            enh_positive_margin_decline,
            enh_positive_margin_benefit,
            enh_negative_margin_decline,
            enh_negative_margin_benefit,
            enh_benefit_before_deductions,
            enh_benefit_after_prodins_ded,
            enh_benefit_after_interim_ded,
            enh_benefit_after_payment_cap,
            enh_total_benefit,
            enh_additional_benefit,
            enh_late_enrolment_penalty,
            enh_bnft_aftr_late_enr_penalty,
            enh_bnft_aftr_applied_bnft_pct,
            enh_lat_en_pnlty_af_apl_bn_pct,
            ratio_adj_reference_margin,
            additive_adj_reference_margin,
            agristability_scenario_id,
            structural_change_code,
            expense_structural_change_code,
            revision_count,
            who_created,
            when_created,
            who_updated,
            when_updated
        ) values (
            nextval('farms.farm_acl_seq'),
            in_administrative_cost_share,
            in_late_application_penalty,
            in_maximum_contribution,
            in_outstanding_fees,
            in_program_year_margin,
            in_prod_insur_deemed_benefit,
            in_pi_deemed_bnft_manual_calc_ind,
            in_program_year_payments_rec,
            in_allocated_reference_margin,
            in_repayment_of_cash_advances,
            in_total_payment,
            in_supply_managed_comm_adj,
            in_producer_share,
            in_federal_contributions,
            in_provincial_contributions,
            in_interim_contributions,
            in_whole_farm_allocation,
            in_tier2_margin_decline,
            in_tier3_margin_decline,
            in_tier2_benefit,
            in_tier3_benefit,
            in_margin_decline,
            in_negative_margin_decline,
            in_negative_margin_benefit,
            in_total_benefit,
            in_adjusted_reference_margin,
            in_unadjusted_reference_margin,
            in_reference_margin_limit,
            in_reference_margin_limit_cap,
            in_ref_marg_lim_for_bnft_calc,
            in_tier2_trigger,
            in_tier3_trigger,
            in_benefit_before_deductions,
            in_benefit_after_pi_ded,
            in_applied_benefit_percent,
            in_benefit_after_appl_ben_pct,
            in_interim_benefit_percent,
            in_benefit_after_interim_ded,
            in_payment_cap,
            in_benefit_after_payment_cap,
            in_late_enrolment_penalty,
            in_bnft_after_late_enrol_penal,
            in_late_enr_pen_af_apl_ben_pct,
            in_standard_benefit,
            in_enh_ref_margin_for_ben_calc,
            in_enh_margin_decline,
            in_enh_positive_margin_decline,
            in_enh_positive_margin_benefit,
            in_enh_negative_margin_decline,
            in_enh_negative_margin_benefit,
            in_enh_benefit_before_ded,
            in_enh_benefit_aft_prodins_ded,
            in_enh_benefit_aft_interim_ded,
            in_enh_benefit_after_payment_cap,
            in_enh_total_benefit,
            in_enh_additional_benefit,
            in_enh_late_enrolment_penalty,
            in_enh_bnft_aftr_late_enr_penalty,
            in_enh_bnft_aftr_applied_bnft_pct,
            in_enh_lat_en_pnlty_af_apl_bn_pct,
            in_ratio_adj_reference_margin,
            in_additive_adj_reference_marg,
            in_agristability_scenario_id,
            in_structural_change_code,
            in_expense_structural_chg_code,
            1,
            in_user_id,
            current_timestamp,
            in_user_id,
            current_timestamp
        )
        returning agristability_claim_id, revision_count
        into io_agristability_claim_id, io_revision_count;
    else
        --
        -- update
        --
        v_revision_count := (io_revision_count + farms_types_pkg.revision_count_increment()::int);

        update farms.farm_agristability_claims
        set administrative_cost_share = in_administrative_cost_share,
            late_application_penalty = in_late_application_penalty,
            maximum_contribution = in_maximum_contribution,
            outstanding_fees = in_outstanding_fees,
            program_year_margin = in_program_year_margin,
            prod_insur_deemed_benefit = in_prod_insur_deemed_benefit,
            program_year_payments_received = in_program_year_payments_rec,
            allocated_reference_margin = in_allocated_reference_margin,
            repayment_of_cash_advances = in_repayment_of_cash_advances,
            total_payment = in_total_payment,
            supply_managed_commodities_adj = in_supply_managed_comm_adj,
            producer_share = in_producer_share,
            federal_contributions = in_federal_contributions,
            provincial_contributions = in_provincial_contributions,
            interim_contributions = in_interim_contributions,
            whole_farm_allocation = in_whole_farm_allocation,
            tier2_margin_decline = in_tier2_margin_decline,
            tier3_margin_decline = in_tier3_margin_decline,
            tier2_benefit = in_tier2_benefit,
            tier3_benefit = in_tier3_benefit,
            margin_decline = in_margin_decline,
            negative_margin_decline = in_negative_margin_decline,
            negative_margin_benefit = in_negative_margin_benefit,
            total_benefit = in_total_benefit,
            adjusted_reference_margin = in_adjusted_reference_margin,
            unadjusted_reference_margin = in_unadjusted_reference_margin,
            reference_margin_limit = in_reference_margin_limit,
            reference_margin_limit_cap = in_reference_margin_limit_cap,
            ref_marg_limit_for_bnft_calc = in_ref_marg_lim_for_bnft_calc,
            tier2_trigger = in_tier2_trigger,
            tier3_trigger = in_tier3_trigger,
            benefit_before_deductions = in_benefit_before_deductions,
            benefit_after_prod_insur_ded = in_benefit_after_pi_ded,
            applied_benefit_percent = in_applied_benefit_percent,
            benefit_after_appl_benefit_pct = in_benefit_after_appl_ben_pct,
            interim_benefit_percent = in_interim_benefit_percent,
            benefit_after_interim_ded = in_benefit_after_interim_ded,
            payment_cap = in_payment_cap,
            benefit_after_payment_cap = in_benefit_after_payment_cap,
            late_enrolment_penalty = in_late_enrolment_penalty,
            bnft_after_late_enrol_penalty = in_bnft_after_late_enrol_penal,
            late_enr_pnlty_aft_apl_ben_pct = in_late_enr_pen_af_apl_ben_pct,
            standard_benefit = in_standard_benefit,
            enh_ref_margin_for_beneft_calc = in_enh_ref_margin_for_ben_calc,
            enh_margin_decline = in_enh_margin_decline,
            enh_positive_margin_decline = in_enh_positive_margin_decline,
            enh_positive_margin_benefit = in_enh_positive_margin_benefit,
            enh_negative_margin_decline = in_enh_negative_margin_decline,
            enh_negative_margin_benefit = in_enh_negative_margin_benefit,
            enh_benefit_before_deductions = in_enh_benefit_before_ded,
            enh_benefit_after_prodins_ded = in_enh_benefit_aft_prodins_ded,
            enh_benefit_after_interim_ded = in_enh_benefit_aft_interim_ded,
            enh_benefit_after_payment_cap = in_enh_benefit_after_payment_cap,
            enh_total_benefit = in_enh_total_benefit,
            enh_additional_benefit = in_enh_additional_benefit,
            enh_late_enrolment_penalty = in_enh_late_enrolment_penalty,
            enh_bnft_aftr_late_enr_penalty = in_enh_bnft_aftr_late_enr_penalty,
            enh_bnft_aftr_applied_bnft_pct = in_enh_bnft_aftr_applied_bnft_pct,
            enh_lat_en_pnlty_af_apl_bn_pct = in_enh_lat_en_pnlty_af_apl_bn_pct,
            ratio_adj_reference_margin = in_ratio_adj_reference_margin,
            additive_adj_reference_margin = in_additive_adj_reference_marg,
            agristability_scenario_id = in_agristability_scenario_id,
            structural_change_code = in_structural_change_code,
            expense_structural_change_code = in_expense_structural_chg_code,
            revision_count = v_revision_count,
            who_updated  = in_user_id,
            when_updated = current_timestamp
        where agristability_claim_id = io_agristability_claim_id
        and revision_count = io_revision_count
        returning agristability_claim_id, revision_count
        into io_agristability_claim_id, io_revision_count;

        get diagnostics v_rows_affected = row_count;
        if v_rows_affected = 0 then
            raise exception '%', farms_types_pkg.invalid_revision_count_msg()
            using errcode = farms_types_pkg.invalid_revision_count_code()::text;
        end if;

    end if;
end;
$$;
