/**
 * Copyright (c) 2023,
 * Government of British Columbia,
 * Canada
 *
 * All rights reserved.
 * This information contained herein may not be used in whole or in part
 * without the express written consent of the Government of British
 * Columbia, Canada.
 */
package ca.bc.gov.srm.farm.chefs;

import static org.junit.jupiter.api.Assertions.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;

import ca.bc.gov.srm.farm.chefs.database.ChefsFormTypeCodes;
import ca.bc.gov.srm.farm.chefs.resource.npp.NppSubmissionDataResource;
import ca.bc.gov.srm.farm.chefs.resource.submission.SubmissionParentResource;
import ca.bc.gov.srm.farm.chefs.resource.submission.SubmissionResource;
import ca.bc.gov.srm.farm.chefs.resource.submission.SubmissionWrapperResource;
import ca.bc.gov.srm.farm.domain.FarmingOperation;
import ca.bc.gov.srm.farm.domain.ProductiveUnitCapacity;
import ca.bc.gov.srm.farm.domain.Scenario;
import ca.bc.gov.srm.farm.exception.ServiceException;
import ca.bc.gov.srm.farm.util.TestUtils;

public class AbstractChefsNppSubmissionTest extends ChefsSubmissionTest {

  @SuppressWarnings("unused")
  private static Logger logger = LoggerFactory.getLogger(AbstractChefsNppSubmissionTest.class);

  protected final String CHEFS_FORM_TYPE = ChefsFormTypeCodes.NPP;

  protected void checkProductiveUnitValuesForEveryCode(NppSubmissionDataResource data, Scenario scenario) {
    FarmingOperation fo = scenario.getFarmingYear().getFarmingOperationByNumber(1);
    assertNotNull(fo);
 
    for (ProductiveUnitCapacity puc : fo.getLocalProductiveUnitCapacities()) {
      switch (puc.getCode()) {
        case "5000": assertEquals(puc.getReportedAmount(), 1.0); break;
        case "5002": assertEquals(puc.getReportedAmount(), 2.0); break;
        case "5006": assertEquals(puc.getReportedAmount(), 3.0); break;
        case "5007": assertEquals(puc.getReportedAmount(), 4.0); break;
        case "5009": assertEquals(puc.getReportedAmount(), 5.0); break;
        case "5010": assertEquals(puc.getReportedAmount(), 6.0); break;
        case "5012": assertEquals(puc.getReportedAmount(), 7.0); break;
        case "5016": assertEquals(puc.getReportedAmount(), 8.0); break;
        case "5018": assertEquals(puc.getReportedAmount(), 9.0); break;
        case "5020": assertEquals(puc.getReportedAmount(), 10.0); break;
        case "5021": assertEquals(puc.getReportedAmount(), 11.0); break;
        case "5022": assertEquals(puc.getReportedAmount(), 12.0); break;
        case "5024": assertEquals(puc.getReportedAmount(), 13.0); break;
 
        case "5014": assertEquals(puc.getReportedAmount(), 14.0); break;
        case "5030": assertEquals(puc.getReportedAmount(), 15.0); break;
        case "5032": assertEquals(puc.getReportedAmount(), 16.0); break;
        case "5033": assertEquals(puc.getReportedAmount(), 17.0); break;
        case "5040": assertEquals(puc.getReportedAmount(), 18.0); break;
        case "5042": assertEquals(puc.getReportedAmount(), 19.0); break;
        case "5044": assertEquals(puc.getReportedAmount(), 20.0); break;
        case "5046": assertEquals(puc.getReportedAmount(), 21.0); break;
        case "5048": assertEquals(puc.getReportedAmount(), 22.0); break;
        case "5050": assertEquals(puc.getReportedAmount(), 23.0); break;
        case "5052": assertEquals(puc.getReportedAmount(), 24.0); break;
        case "5054": assertEquals(puc.getReportedAmount(), 25.0); break;
        case "5056": assertEquals(puc.getReportedAmount(), 26.0); break;
        case "7054": assertEquals(puc.getReportedAmount(), 27.0); break;
        case "5058": assertEquals(puc.getReportedAmount(), 28.0); break;
 
        case "6": assertEquals(puc.getReportedAmount(), 29.0); break;
        case "5034": assertEquals(puc.getReportedAmount(), 30.0); break;
        case "6850": assertEquals(puc.getReportedAmount(), 31.0); break;
        case "6851": assertEquals(puc.getReportedAmount(), 32.0); break;
        case "6852": assertEquals(puc.getReportedAmount(), 33.0); break;
        case "6854": assertEquals(puc.getReportedAmount(), 34.0); break;
        case "6855": assertEquals(puc.getReportedAmount(), 35.0); break;
        case "6856": assertEquals(puc.getReportedAmount(), 36.0); break;
        case "6858": assertEquals(puc.getReportedAmount(), 37.0); break;
        case "6860": assertEquals(puc.getReportedAmount(), 38.0); break;
        case "6862": assertEquals(puc.getReportedAmount(), 39.0); break;
        case "6864": assertEquals(puc.getReportedAmount(), 40.0); break;
        case "6866": assertEquals(puc.getReportedAmount(), 41.0); break;
        case "6867": assertEquals(puc.getReportedAmount(), 42.0); break;
        case "6868": assertEquals(puc.getReportedAmount(), 43.0); break;
        case "6869": assertEquals(puc.getReportedAmount(), 44.0); break;
        case "6870": assertEquals(puc.getReportedAmount(), 45.0); break;
        case "6872": assertEquals(puc.getReportedAmount(), 46.0); break;
        case "6874": assertEquals(puc.getReportedAmount(), 47.0); break;
        case "6876": assertEquals(puc.getReportedAmount(), 48.0); break;
        case "6877": assertEquals(puc.getReportedAmount(), 49.0); break;
        case "6878": assertEquals(puc.getReportedAmount(), 50.0); break;
        case "6879": assertEquals(puc.getReportedAmount(), 51.0); break;
        case "6880": assertEquals(puc.getReportedAmount(), 52.0); break;
        case "6881": assertEquals(puc.getReportedAmount(), 53.0); break;
        case "6882": assertEquals(puc.getReportedAmount(), 54.0); break;
        case "6883": assertEquals(puc.getReportedAmount(), 55.0); break;
        case "6884": assertEquals(puc.getReportedAmount(), 56.0); break;
        case "6886": assertEquals(puc.getReportedAmount(), 57.0); break;
        case "6888": assertEquals(puc.getReportedAmount(), 58.0); break;
        case "6890": assertEquals(puc.getReportedAmount(), 59.0); break;
        case "6892": assertEquals(puc.getReportedAmount(), 60.0); break;
        case "6893": assertEquals(puc.getReportedAmount(), 61.0); break;
        case "6894": assertEquals(puc.getReportedAmount(), 62.0); break;
        case "6896": assertEquals(puc.getReportedAmount(), 63.0); break;
        case "6898": assertEquals(puc.getReportedAmount(), 64.0); break;
        case "6900": assertEquals(puc.getReportedAmount(), 65.0); break;
        case "6902": assertEquals(puc.getReportedAmount(), 66.0); break;
        case "6903": assertEquals(puc.getReportedAmount(), 67.0); break;
        case "6904": assertEquals(puc.getReportedAmount(), 68.0); break;
        case "6920": assertEquals(puc.getReportedAmount(), 69.0); break;
        case "6922": assertEquals(puc.getReportedAmount(), 70.0); break;
        case "6932": assertEquals(puc.getReportedAmount(), 71.0); break;
        case "6934": assertEquals(puc.getReportedAmount(), 72.0); break;
        case "6946": assertEquals(puc.getReportedAmount(), 73.0); break;
        case "6972": assertEquals(puc.getReportedAmount(), 75.0); break;
        case "6974": assertEquals(puc.getReportedAmount(), 76.0); break;
        case "6975": assertEquals(puc.getReportedAmount(), 77.0); break;
        case "6976": assertEquals(puc.getReportedAmount(), 78.0); break;
        case "6978": assertEquals(puc.getReportedAmount(), 79.0); break;
        case "6980": assertEquals(puc.getReportedAmount(), 80.0); break;
        case "6982": assertEquals(puc.getReportedAmount(), 81.0); break;
        case "6983": assertEquals(puc.getReportedAmount(), 82.0); break;
        case "6984": assertEquals(puc.getReportedAmount(), 83.0); break;
        case "6986": assertEquals(puc.getReportedAmount(), 84.0); break;
        case "6988": assertEquals(puc.getReportedAmount(), 85.0); break;
        case "6998": assertEquals(puc.getReportedAmount(), 86.0); break;
        case "7000": assertEquals(puc.getReportedAmount(), 87.0); break;
        case "7002": assertEquals(puc.getReportedAmount(), 88.0); break;
        case "7004": assertEquals(puc.getReportedAmount(), 89.0); break;
        case "7006": assertEquals(puc.getReportedAmount(), 90.0); break;
        case "7008": assertEquals(puc.getReportedAmount(), 91.0); break;
        case "7010": assertEquals(puc.getReportedAmount(), 92.0); break;
        case "7012": assertEquals(puc.getReportedAmount(), 93.0); break;
        case "7014": assertEquals(puc.getReportedAmount(), 94.0); break;
        case "7015": assertEquals(puc.getReportedAmount(), 95.0); break;
        case "7016": assertEquals(puc.getReportedAmount(), 96.0); break;
        case "7018": assertEquals(puc.getReportedAmount(), 97.0); break;
        case "7020": assertEquals(puc.getReportedAmount(), 98.0); break;
        case "7022": assertEquals(puc.getReportedAmount(), 99.0); break;
        case "7024": assertEquals(puc.getReportedAmount(), 100.0); break;
        case "7026": assertEquals(puc.getReportedAmount(), 101.0); break;
        case "7030": assertEquals(puc.getReportedAmount(), 102.0); break;
        case "7032": assertEquals(puc.getReportedAmount(), 103.0); break;
        case "7034": assertEquals(puc.getReportedAmount(), 104.0); break;
        case "7035": assertEquals(puc.getReportedAmount(), 105.0); break;
        case "7036": assertEquals(puc.getReportedAmount(), 106.0); break;
        case "7037": assertEquals(puc.getReportedAmount(), 107.0); break;
        case "7038": assertEquals(puc.getReportedAmount(), 108.0); break;
        case "7039": assertEquals(puc.getReportedAmount(), 109.0); break;
        case "7040": assertEquals(puc.getReportedAmount(), 110.0); break;
        case "7042": assertEquals(puc.getReportedAmount(), 111.0); break;
        case "7044": assertEquals(puc.getReportedAmount(), 112.0); break;
        case "7046": assertEquals(puc.getReportedAmount(), 113.0); break;
        case "7047": assertEquals(puc.getReportedAmount(), 114.0); break;
        case "7048": assertEquals(puc.getReportedAmount(), 115.0); break;
        case "7049": assertEquals(puc.getReportedAmount(), 116.0); break;
        case "7052": assertEquals(puc.getReportedAmount(), 117.0); break;
        case "7056": assertEquals(puc.getReportedAmount(), 118.0); break;
        case "7057": assertEquals(puc.getReportedAmount(), 119.0); break;
        case "7058": assertEquals(puc.getReportedAmount(), 120.0); break;
        case "7060": assertEquals(puc.getReportedAmount(), 121.0); break;
        case "7062": assertEquals(puc.getReportedAmount(), 122.0); break;
        case "7064": assertEquals(puc.getReportedAmount(), 123.0); break;
        case "7068": assertEquals(puc.getReportedAmount(), 125.0); break;
        case "7069": assertEquals(puc.getReportedAmount(), 126.0); break;
        case "7070": assertEquals(puc.getReportedAmount(), 127.0); break;
        case "7072": assertEquals(puc.getReportedAmount(), 128.0); break;
        case "7074": assertEquals(puc.getReportedAmount(), 129.0); break;
        case "7078": assertEquals(puc.getReportedAmount(), 130.0); break;
        case "7080": assertEquals(puc.getReportedAmount(), 131.0); break;
        case "7082": assertEquals(puc.getReportedAmount(), 132.0); break;
        case "7083": assertEquals(puc.getReportedAmount(), 133.0); break;
        case "7084": assertEquals(puc.getReportedAmount(), 134.0); break;
        case "7086": assertEquals(puc.getReportedAmount(), 135.0); break;
        case "7087": assertEquals(puc.getReportedAmount(), 136.0); break;
        case "7088": assertEquals(puc.getReportedAmount(), 137.0); break;
        case "7094": assertEquals(puc.getReportedAmount(), 138.0); break;
        case "7095": assertEquals(puc.getReportedAmount(), 139.0); break;
        case "7098": assertEquals(puc.getReportedAmount(), 140.0); break;
        case "7099": assertEquals(puc.getReportedAmount(), 141.0); break;
        case "7100": assertEquals(puc.getReportedAmount(), 142.0); break;
        case "7200": assertEquals(puc.getReportedAmount(), 143.0); break;
 
        case "4784": assertEquals(puc.getReportedAmount(), 144.0); break;
        case "5100": assertEquals(puc.getReportedAmount(), 145.0); break;
        case "5370": assertEquals(puc.getReportedAmount(), 147.0); break;
        case "5372": assertEquals(puc.getReportedAmount(), 148.0); break;
        case "5374": assertEquals(puc.getReportedAmount(), 149.0); break;
        case "5369": assertEquals(puc.getReportedAmount(), 150.0); break;
        case "5375": assertEquals(puc.getReportedAmount(), 151.0); break;
        case "5376": assertEquals(puc.getReportedAmount(), 152.0); break;
        case "5378": assertEquals(puc.getReportedAmount(), 153.0); break;
        case "5380": assertEquals(puc.getReportedAmount(), 154.0); break;
        case "5382": assertEquals(puc.getReportedAmount(), 155.0); break;
        case "5384": assertEquals(puc.getReportedAmount(), 156.0); break;
        case "5386": assertEquals(puc.getReportedAmount(), 157.0); break;
        case "5388": assertEquals(puc.getReportedAmount(), 158.0); break;
        case "5390": assertEquals(puc.getReportedAmount(), 159.0); break;
        case "5392": assertEquals(puc.getReportedAmount(), 160.0); break;
        case "5394": assertEquals(puc.getReportedAmount(), 161.0); break;
        case "5468": assertEquals(puc.getReportedAmount(), 162.0); break;
        case "5446": assertEquals(puc.getReportedAmount(), 163.0); break;
        case "5396": assertEquals(puc.getReportedAmount(), 164.0); break;
        case "5398": assertEquals(puc.getReportedAmount(), 165.0); break;
        case "5400": assertEquals(puc.getReportedAmount(), 166.0); break;
        case "5402": assertEquals(puc.getReportedAmount(), 167.0); break;
        case "5404": assertEquals(puc.getReportedAmount(), 168.0); break;
        case "5406": assertEquals(puc.getReportedAmount(), 169.0); break;
        case "5408": assertEquals(puc.getReportedAmount(), 170.0); break;
        case "5410": assertEquals(puc.getReportedAmount(), 171.0); break;
        case "5412": assertEquals(puc.getReportedAmount(), 172.0); break;
        case "5414": assertEquals(puc.getReportedAmount(), 173.0); break;
        case "5416": assertEquals(puc.getReportedAmount(), 174.0); break;
        case "5418": assertEquals(puc.getReportedAmount(), 175.0); break;
        case "5420": assertEquals(puc.getReportedAmount(), 176.0); break;
        case "5422": assertEquals(puc.getReportedAmount(), 177.0); break;
        case "5424": assertEquals(puc.getReportedAmount(), 178.0); break;
        case "5426": assertEquals(puc.getReportedAmount(), 179.0); break;
        case "5428": assertEquals(puc.getReportedAmount(), 180.0); break;
        case "5430": assertEquals(puc.getReportedAmount(), 181.0); break;
        case "5432": assertEquals(puc.getReportedAmount(), 182.0); break;
        case "5434": assertEquals(puc.getReportedAmount(), 183.0); break;
        case "5436": assertEquals(puc.getReportedAmount(), 184.0); break;
        case "5438": assertEquals(puc.getReportedAmount(), 185.0); break;
        case "5440": assertEquals(puc.getReportedAmount(), 186.0); break;
        case "5442": assertEquals(puc.getReportedAmount(), 187.0); break;
        case "5444": assertEquals(puc.getReportedAmount(), 188.0); break;
        case "5448": assertEquals(puc.getReportedAmount(), 189.0); break;
        case "5450": assertEquals(puc.getReportedAmount(), 190.0); break;
        case "5452": assertEquals(puc.getReportedAmount(), 191.0); break;
        case "5454": assertEquals(puc.getReportedAmount(), 192.0); break;
        case "5456": assertEquals(puc.getReportedAmount(), 193.0); break;
        case "5458": assertEquals(puc.getReportedAmount(), 194.0); break;
        case "5460": assertEquals(puc.getReportedAmount(), 195.0); break;
        case "5462": assertEquals(puc.getReportedAmount(), 196.0); break;
        case "5464": assertEquals(puc.getReportedAmount(), 197.0); break;
        case "5466": assertEquals(puc.getReportedAmount(), 198.0); break;
        case "5240": assertEquals(puc.getReportedAmount(), 199.0); break;
        case "5242": assertEquals(puc.getReportedAmount(), 200.0); break;
        case "5244": assertEquals(puc.getReportedAmount(), 201.0); break;
        case "5246": assertEquals(puc.getReportedAmount(), 202.0); break;
        case "5248": assertEquals(puc.getReportedAmount(), 203.0); break;
        case "5540": assertEquals(puc.getReportedAmount(), 204.0); break;
        case "5542": assertEquals(puc.getReportedAmount(), 205.0); break;
        case "5544": assertEquals(puc.getReportedAmount(), 206.0); break;
        case "5250": assertEquals(puc.getReportedAmount(), 207.0); break;
        case "5252": assertEquals(puc.getReportedAmount(), 208.0); break;
        case "5254": assertEquals(puc.getReportedAmount(), 209.0); break;
        case "5261": assertEquals(puc.getReportedAmount(), 210.0); break;
        case "5290": assertEquals(puc.getReportedAmount(), 211.0); break;
        case "5292": assertEquals(puc.getReportedAmount(), 212.0); break;
        case "5294": assertEquals(puc.getReportedAmount(), 213.0); break;
        case "5300": assertEquals(puc.getReportedAmount(), 214.0); break;
        case "5302": assertEquals(puc.getReportedAmount(), 215.0); break;
        case "5303": assertEquals(puc.getReportedAmount(), 216.0); break;
        case "5304": assertEquals(puc.getReportedAmount(), 217.0); break;
        case "5306": assertEquals(puc.getReportedAmount(), 218.0); break;
        case "5330": assertEquals(puc.getReportedAmount(), 219.0); break;
        case "5310": assertEquals(puc.getReportedAmount(), 220.0); break;
        case "5312": assertEquals(puc.getReportedAmount(), 221.0); break;
        case "5314": assertEquals(puc.getReportedAmount(), 222.0); break;
        case "5316": assertEquals(puc.getReportedAmount(), 223.0); break;
        case "5318": assertEquals(puc.getReportedAmount(), 224.0); break;
        case "5322": assertEquals(puc.getReportedAmount(), 225.0); break;
        case "5324": assertEquals(puc.getReportedAmount(), 226.0); break;
        case "5325": assertEquals(puc.getReportedAmount(), 227.0); break;
        case "5326": assertEquals(puc.getReportedAmount(), 228.0); break;
        case "5328": assertEquals(puc.getReportedAmount(), 229.0); break;
        case "5340": assertEquals(puc.getReportedAmount(), 230.0); break;
        case "5360": assertEquals(puc.getReportedAmount(), 231.0); break;
        case "5350": assertEquals(puc.getReportedAmount(), 232.0); break;
        case "5352": assertEquals(puc.getReportedAmount(), 233.0); break;
        case "5354": assertEquals(puc.getReportedAmount(), 234.0); break;
        case "5356": assertEquals(puc.getReportedAmount(), 235.0); break;
        case "5358": assertEquals(puc.getReportedAmount(), 236.0); break;
        case "5550": assertEquals(puc.getReportedAmount(), 237.0); break;
        case "6826": assertEquals(puc.getReportedAmount(), 238.0); break;
        case "5750": assertEquals(puc.getReportedAmount(), 239.0); break;
        case "5752": assertEquals(puc.getReportedAmount(), 240.0); break;
        case "5754": assertEquals(puc.getReportedAmount(), 241.0); break;
        case "5070": assertEquals(puc.getReportedAmount(), 242.0); break;
        case "5072": assertEquals(puc.getReportedAmount(), 243.0); break;
        case "5074": assertEquals(puc.getReportedAmount(), 244.0); break;
        case "5822": assertEquals(puc.getReportedAmount(), 245.0); break;
        case "5760": assertEquals(puc.getReportedAmount(), 246.0); break;
        case "5762": assertEquals(puc.getReportedAmount(), 247.0); break;
        case "5764": assertEquals(puc.getReportedAmount(), 248.0); break;
        case "5766": assertEquals(puc.getReportedAmount(), 249.0); break;
        case "5768": assertEquals(puc.getReportedAmount(), 250.0); break;
        case "5770": assertEquals(puc.getReportedAmount(), 251.0); break;
        case "5820": assertEquals(puc.getReportedAmount(), 252.0); break;
        case "5772": assertEquals(puc.getReportedAmount(), 253.0); break;
        case "5774": assertEquals(puc.getReportedAmount(), 254.0); break;
        case "5776": assertEquals(puc.getReportedAmount(), 255.0); break;
        case "5778": assertEquals(puc.getReportedAmount(), 256.0); break;
        case "5780": assertEquals(puc.getReportedAmount(), 257.0); break;
        case "5782": assertEquals(puc.getReportedAmount(), 258.0); break;
        case "5784": assertEquals(puc.getReportedAmount(), 259.0); break;
        case "5786": assertEquals(puc.getReportedAmount(), 260.0); break;
        case "5788": assertEquals(puc.getReportedAmount(), 261.0); break;
        case "5790": assertEquals(puc.getReportedAmount(), 262.0); break;
        case "5792": assertEquals(puc.getReportedAmount(), 263.0); break;
        case "5794": assertEquals(puc.getReportedAmount(), 264.0); break;
        case "5821": assertEquals(puc.getReportedAmount(), 265.0); break;
        case "5796": assertEquals(puc.getReportedAmount(), 266.0); break;
        case "5798": assertEquals(puc.getReportedAmount(), 267.0); break;
        case "5800": assertEquals(puc.getReportedAmount(), 268.0); break;
        case "5802": assertEquals(puc.getReportedAmount(), 269.0); break;
        case "5804": assertEquals(puc.getReportedAmount(), 270.0); break;
        case "5806": assertEquals(puc.getReportedAmount(), 271.0); break;
        case "5808": assertEquals(puc.getReportedAmount(), 272.0); break;
        case "5810": assertEquals(puc.getReportedAmount(), 273.0); break;
        case "5812": assertEquals(puc.getReportedAmount(), 274.0); break;
        case "5814": assertEquals(puc.getReportedAmount(), 275.0); break;
        case "5816": assertEquals(puc.getReportedAmount(), 276.0); break;
        case "5818": assertEquals(puc.getReportedAmount(), 277.0); break;
        case "5830": assertEquals(puc.getReportedAmount(), 278.0); break;
        case "5832": assertEquals(puc.getReportedAmount(), 279.0); break;
        case "5834": assertEquals(puc.getReportedAmount(), 280.0); break;
        case "5836": assertEquals(puc.getReportedAmount(), 281.0); break;
        case "5840": assertEquals(puc.getReportedAmount(), 282.0); break;
        case "5841": assertEquals(puc.getReportedAmount(), 283.0); break;
        case "5850": assertEquals(puc.getReportedAmount(), 284.0); break;
        case "5852": assertEquals(puc.getReportedAmount(), 285.0); break;
        case "5854": assertEquals(puc.getReportedAmount(), 286.0); break;
        case "5856": assertEquals(puc.getReportedAmount(), 287.0); break;
        case "5858": assertEquals(puc.getReportedAmount(), 288.0); break;
        case "5860": assertEquals(puc.getReportedAmount(), 289.0); break;
        case "5862": assertEquals(puc.getReportedAmount(), 290.0); break;
        case "5864": assertEquals(puc.getReportedAmount(), 291.0); break;
        case "5866": assertEquals(puc.getReportedAmount(), 292.0); break;
        case "5868": assertEquals(puc.getReportedAmount(), 293.0); break;
        case "5870": assertEquals(puc.getReportedAmount(), 294.0); break;
        case "5872": assertEquals(puc.getReportedAmount(), 295.0); break;
        case "5874": assertEquals(puc.getReportedAmount(), 296.0); break;
        case "5876": assertEquals(puc.getReportedAmount(), 297.0); break;
        case "5878": assertEquals(puc.getReportedAmount(), 298.0); break;
        case "5880": assertEquals(puc.getReportedAmount(), 299.0); break;
        case "5882": assertEquals(puc.getReportedAmount(), 300.0); break;
        case "5884": assertEquals(puc.getReportedAmount(), 301.0); break;
        case "5886": assertEquals(puc.getReportedAmount(), 302.0); break;
        case "5968": assertEquals(puc.getReportedAmount(), 303.0); break;
        case "5900": assertEquals(puc.getReportedAmount(), 304.0); break;
        case "5500": assertEquals(puc.getReportedAmount(), 305.0); break;
        case "5502": assertEquals(puc.getReportedAmount(), 306.0); break;
        case "5504": assertEquals(puc.getReportedAmount(), 307.0); break;
        case "5506": assertEquals(puc.getReportedAmount(), 308.0); break;
        case "5508": assertEquals(puc.getReportedAmount(), 309.0); break;
        case "5510": assertEquals(puc.getReportedAmount(), 310.0); break;
        case "5512": assertEquals(puc.getReportedAmount(), 311.0); break;
        case "5514": assertEquals(puc.getReportedAmount(), 312.0); break;
        case "5516": assertEquals(puc.getReportedAmount(), 313.0); break;
        case "5518": assertEquals(puc.getReportedAmount(), 314.0); break;
        case "5520": assertEquals(puc.getReportedAmount(), 315.0); break;
        case "5076": assertEquals(puc.getReportedAmount(), 316.0); break;
        case "5078": assertEquals(puc.getReportedAmount(), 317.0); break;
        case "5080": assertEquals(puc.getReportedAmount(), 318.0); break;
        case "5259": assertEquals(puc.getReportedAmount(), 319.0); break;
        case "5910": assertEquals(puc.getReportedAmount(), 320.0); break;
        case "5912": assertEquals(puc.getReportedAmount(), 321.0); break;
        case "5914": assertEquals(puc.getReportedAmount(), 322.0); break;
        case "5916": assertEquals(puc.getReportedAmount(), 323.0); break;
        case "5918": assertEquals(puc.getReportedAmount(), 324.0); break;
        case "5920": assertEquals(puc.getReportedAmount(), 325.0); break;
        case "5930": assertEquals(puc.getReportedAmount(), 326.0); break;
        case "5932": assertEquals(puc.getReportedAmount(), 327.0); break;
        case "5934": assertEquals(puc.getReportedAmount(), 328.0); break;
        case "5936": assertEquals(puc.getReportedAmount(), 329.0); break;
        case "5907": assertEquals(puc.getReportedAmount(), 330.0); break;
        case "5908": assertEquals(puc.getReportedAmount(), 331.0); break;
        case "5940": assertEquals(puc.getReportedAmount(), 332.0); break;
        case "5942": assertEquals(puc.getReportedAmount(), 333.0); break;
        case "5944": assertEquals(puc.getReportedAmount(), 334.0); break;
        case "5946": assertEquals(puc.getReportedAmount(), 335.0); break;
        case "5082": assertEquals(puc.getReportedAmount(), 336.0); break;
        case "5084": assertEquals(puc.getReportedAmount(), 337.0); break;
        case "5086": assertEquals(puc.getReportedAmount(), 338.0); break;
        case "5950": assertEquals(puc.getReportedAmount(), 339.0); break;
        case "5952": assertEquals(puc.getReportedAmount(), 340.0); break;
        case "5954": assertEquals(puc.getReportedAmount(), 341.0); break;
        case "5956": assertEquals(puc.getReportedAmount(), 342.0); break;
        case "5964": assertEquals(puc.getReportedAmount(), 343.0); break;
        case "5958": assertEquals(puc.getReportedAmount(), 344.0); break;
        case "5960": assertEquals(puc.getReportedAmount(), 345.0); break;
        case "5962": assertEquals(puc.getReportedAmount(), 346.0); break;
        case "5970": assertEquals(puc.getReportedAmount(), 347.0); break;
        case "5972": assertEquals(puc.getReportedAmount(), 348.0); break;
        case "5974": assertEquals(puc.getReportedAmount(), 349.0); break;
        case "5980": assertEquals(puc.getReportedAmount(), 350.0); break;
        case "5982": assertEquals(puc.getReportedAmount(), 351.0); break;
        case "5984": assertEquals(puc.getReportedAmount(), 352.0); break;
        case "6000": assertEquals(puc.getReportedAmount(), 353.0); break;
 
        case "5560": assertEquals(puc.getReportedAmount(), 1000.0); break;
        case "5562": assertEquals(puc.getReportedAmount(), 1001.0); break;
        case "5564": assertEquals(puc.getReportedAmount(), 1002.0); break;
        case "5566": assertEquals(puc.getReportedAmount(), 1003.0); break;
        case "5568": assertEquals(puc.getReportedAmount(), 1004.0); break;
        case "5570": assertEquals(puc.getReportedAmount(), 1005.0); break;
        case "5572": assertEquals(puc.getReportedAmount(), 1006.0); break;
        case "5574": assertEquals(puc.getReportedAmount(), 1007.0); break;
        case "5576": assertEquals(puc.getReportedAmount(), 1008.0); break;
        case "5578": assertEquals(puc.getReportedAmount(), 1009.0); break;
        case "5579": assertEquals(puc.getReportedAmount(), 1010.0); break;
        case "5580": assertEquals(puc.getReportedAmount(), 1011.0); break;
        case "5582": assertEquals(puc.getReportedAmount(), 1012.0); break;
        case "5583": assertEquals(puc.getReportedAmount(), 1013.0); break;
        case "5586": assertEquals(puc.getReportedAmount(), 1014.0); break;
        case "5588": assertEquals(puc.getReportedAmount(), 1015.0); break;
 
        case "5600": assertEquals(puc.getReportedAmount(), 1016.0); break;
        case "5603": assertEquals(puc.getReportedAmount(), 1017.0); break;
        case "5602": assertEquals(puc.getReportedAmount(), 1018.0); break;
        case "5604": assertEquals(puc.getReportedAmount(), 1019.0); break;
        case "5606": assertEquals(puc.getReportedAmount(), 1020.0); break;
        case "5608": assertEquals(puc.getReportedAmount(), 1021.0); break;
        case "5610": assertEquals(puc.getReportedAmount(), 1022.0); break;
        case "5736": assertEquals(puc.getReportedAmount(), 1023.0); break;
        case "5612": assertEquals(puc.getReportedAmount(), 1024.0); break;
        case "5614": assertEquals(puc.getReportedAmount(), 1025.0); break;
        case "5724": assertEquals(puc.getReportedAmount(), 1026.0); break;
        case "5726": assertEquals(puc.getReportedAmount(), 1027.0); break;
        case "5723": assertEquals(puc.getReportedAmount(), 1028.0); break;
        case "5725": assertEquals(puc.getReportedAmount(), 1029.0); break;
        case "5729": assertEquals(puc.getReportedAmount(), 1030.0); break;
        case "5620": assertEquals(puc.getReportedAmount(), 1031.0); break;
        case "5622": assertEquals(puc.getReportedAmount(), 1032.0); break;
        case "5624": assertEquals(puc.getReportedAmount(), 1033.0); break;
        case "5619": assertEquals(puc.getReportedAmount(), 1034.0); break;
        case "5628": assertEquals(puc.getReportedAmount(), 1035.0); break;
        case "5732": assertEquals(puc.getReportedAmount(), 1036.0); break;
        case "5731": assertEquals(puc.getReportedAmount(), 1037.0); break;
        case "5734": assertEquals(puc.getReportedAmount(), 1038.0); break;
        case "5733": assertEquals(puc.getReportedAmount(), 1039.0); break;
        case "5636": assertEquals(puc.getReportedAmount(), 1040.0); break;
        case "5638": assertEquals(puc.getReportedAmount(), 1041.0); break;
        case "5640": assertEquals(puc.getReportedAmount(), 1042.0); break;
        case "5642": assertEquals(puc.getReportedAmount(), 1043.0); break;
        case "5727": assertEquals(puc.getReportedAmount(), 1044.0); break;
        case "5728": assertEquals(puc.getReportedAmount(), 1045.0); break;
        case "5644": assertEquals(puc.getReportedAmount(), 1046.0); break;
        case "5646": assertEquals(puc.getReportedAmount(), 1047.0); break;
        case "5648": assertEquals(puc.getReportedAmount(), 1048.0); break;
        case "5650": assertEquals(puc.getReportedAmount(), 1049.0); break;
        case "5652": assertEquals(puc.getReportedAmount(), 1050.0); break;
        case "5671": assertEquals(puc.getReportedAmount(), 1051.0); break;
        case "5656": assertEquals(puc.getReportedAmount(), 1052.0); break;
        case "5658": assertEquals(puc.getReportedAmount(), 1053.0); break;
        case "5660": assertEquals(puc.getReportedAmount(), 1054.0); break;
        case "5662": assertEquals(puc.getReportedAmount(), 1055.0); break;
        case "5664": assertEquals(puc.getReportedAmount(), 1056.0); break;
        case "5666": assertEquals(puc.getReportedAmount(), 1057.0); break;
        case "5668": assertEquals(puc.getReportedAmount(), 1058.0); break;
        case "5670": assertEquals(puc.getReportedAmount(), 1059.0); break;
        case "5672": assertEquals(puc.getReportedAmount(), 1060.0); break;
        case "5674": assertEquals(puc.getReportedAmount(), 1061.0); break;
        case "5676": assertEquals(puc.getReportedAmount(), 1062.0); break;
        case "5680": assertEquals(puc.getReportedAmount(), 1063.0); break;
        case "5682": assertEquals(puc.getReportedAmount(), 1064.0); break;
        case "5684": assertEquals(puc.getReportedAmount(), 1065.0); break;
        case "5686": assertEquals(puc.getReportedAmount(), 1066.0); break;
        case "5688": assertEquals(puc.getReportedAmount(), 1067.0); break;
        case "5690": assertEquals(puc.getReportedAmount(), 1068.0); break;
        case "5592": assertEquals(puc.getReportedAmount(), 1069.0); break;
        case "5596": assertEquals(puc.getReportedAmount(), 1070.0); break;
        case "5593": assertEquals(puc.getReportedAmount(), 1071.0); break;
        case "5597": assertEquals(puc.getReportedAmount(), 1072.0); break;
        case "5595": assertEquals(puc.getReportedAmount(), 1073.0); break;
        case "5599": assertEquals(puc.getReportedAmount(), 1074.0); break;
        case "5594": assertEquals(puc.getReportedAmount(), 1075.0); break;
        case "5598": assertEquals(puc.getReportedAmount(), 1076.0); break;
        case "5699": assertEquals(puc.getReportedAmount(), 1077.0); break;
        case "5696": assertEquals(puc.getReportedAmount(), 1078.0); break;
        case "5698": assertEquals(puc.getReportedAmount(), 1079.0); break;
        case "5700": assertEquals(puc.getReportedAmount(), 1080.0); break;
        case "5702": assertEquals(puc.getReportedAmount(), 1081.0); break;
        case "5693": assertEquals(puc.getReportedAmount(), 1082.0); break;
        case "5695": assertEquals(puc.getReportedAmount(), 1083.0); break;
        case "5691": assertEquals(puc.getReportedAmount(), 1084.0); break;
        case "5683": assertEquals(puc.getReportedAmount(), 1085.0); break;
        case "5685": assertEquals(puc.getReportedAmount(), 1086.0); break;
        case "5659": assertEquals(puc.getReportedAmount(), 1087.0); break;
        case "5689": assertEquals(puc.getReportedAmount(), 1088.0); break;
        case "5687": assertEquals(puc.getReportedAmount(), 1089.0); break;
        case "5615": assertEquals(puc.getReportedAmount(), 1090.0); break;
        case "5742": assertEquals(puc.getReportedAmount(), 1091.0); break;
        case "5704": assertEquals(puc.getReportedAmount(), 1092.0); break;
        case "5706": assertEquals(puc.getReportedAmount(), 1093.0); break;
        case "5709": assertEquals(puc.getReportedAmount(), 1094.0); break;
        case "5708": assertEquals(puc.getReportedAmount(), 1095.0); break;
        case "5714": assertEquals(puc.getReportedAmount(), 1096.0); break;
        case "5716": assertEquals(puc.getReportedAmount(), 1097.0); break;
        case "5718": assertEquals(puc.getReportedAmount(), 1098.0); break;
        case "5730": assertEquals(puc.getReportedAmount(), 1099.0); break;
        case "5720": assertEquals(puc.getReportedAmount(), 1100.0); break;
        case "5722": assertEquals(puc.getReportedAmount(), 1101.0); break;
 
        case "6930": assertEquals(puc.getReportedAmount(), 354.0); break;
        case "6931": assertEquals(puc.getReportedAmount(), 355.0); break;
        case "6937": assertEquals(puc.getReportedAmount(), 356.0); break;
        case "6938": assertEquals(puc.getReportedAmount(), 357.0); break;
        case "6940": assertEquals(puc.getReportedAmount(), 358.0); break;
        case "6941": assertEquals(puc.getReportedAmount(), 359.0); break;
        case "6942": assertEquals(puc.getReportedAmount(), 360.0); break;
        case "6943": assertEquals(puc.getReportedAmount(), 361.0); break;
        case "6944": assertEquals(puc.getReportedAmount(), 362.0); break;
        case "6945": assertEquals(puc.getReportedAmount(), 363.0); break;
        case "6949": assertEquals(puc.getReportedAmount(), 364.0); break;
        case "6950": assertEquals(puc.getReportedAmount(), 365.0); break;
        case "6951": assertEquals(puc.getReportedAmount(), 366.0); break;
        case "6952": assertEquals(puc.getReportedAmount(), 367.0); break;
        case "6953": assertEquals(puc.getReportedAmount(), 368.0); break;
        case "6954": assertEquals(puc.getReportedAmount(), 369.0); break;
        case "6955": assertEquals(puc.getReportedAmount(), 370.0); break;
        case "6956": assertEquals(puc.getReportedAmount(), 371.0); break;
        case "6957": assertEquals(puc.getReportedAmount(), 372.0); break;
        case "6958": assertEquals(puc.getReportedAmount(), 373.0); break;
        case "6959": assertEquals(puc.getReportedAmount(), 374.0); break;
        case "6965": assertEquals(puc.getReportedAmount(), 375.0); break;
        case "7028": assertEquals(puc.getReportedAmount(), 376.0); break;
        case "7073": assertEquals(puc.getReportedAmount(), 378.0); break;
        case "7076": assertEquals(puc.getReportedAmount(), 379.0); break;
        case "7090": assertEquals(puc.getReportedAmount(), 380.0); break;
        case "7092": assertEquals(puc.getReportedAmount(), 381.0); break;
        case "7101": assertEquals(puc.getReportedAmount(), 382.0); break;
        case "7102": assertEquals(puc.getReportedAmount(), 383.0); break;
        case "7103": assertEquals(puc.getReportedAmount(), 384.0); break;
        case "7104": assertEquals(puc.getReportedAmount(), 385.0); break;
        case "7106": assertEquals(puc.getReportedAmount(), 386.0); break;
        case "7108": assertEquals(puc.getReportedAmount(), 387.0); break;
        case "7110": assertEquals(puc.getReportedAmount(), 388.0); break;
        case "7112": assertEquals(puc.getReportedAmount(), 389.0); break;
        case "7114": assertEquals(puc.getReportedAmount(), 390.0); break;
        case "7115": assertEquals(puc.getReportedAmount(), 391.0); break;
        case "7116": assertEquals(puc.getReportedAmount(), 392.0); break;
        case "7117": assertEquals(puc.getReportedAmount(), 393.0); break;
        case "7118": assertEquals(puc.getReportedAmount(), 394.0); break;
        case "7120": assertEquals(puc.getReportedAmount(), 395.0); break;
        case "7122": assertEquals(puc.getReportedAmount(), 396.0); break;
        case "7124": assertEquals(puc.getReportedAmount(), 397.0); break;
        case "7126": assertEquals(puc.getReportedAmount(), 398.0); break;
        case "7128": assertEquals(puc.getReportedAmount(), 399.0); break;
        case "7129": assertEquals(puc.getReportedAmount(), 400.0); break;
        case "7130": assertEquals(puc.getReportedAmount(), 401.0); break;
        case "7132": assertEquals(puc.getReportedAmount(), 402.0); break;
        case "7134": assertEquals(puc.getReportedAmount(), 403.0); break;
        case "7140": assertEquals(puc.getReportedAmount(), 404.0); break;
        case "7142": assertEquals(puc.getReportedAmount(), 405.0); break;
        case "7144": assertEquals(puc.getReportedAmount(), 406.0); break;
        case "7146": assertEquals(puc.getReportedAmount(), 407.0); break;
        case "7148": assertEquals(puc.getReportedAmount(), 408.0); break;
 
        case "104": assertEquals(puc.getReportedAmount(), 409.0); break;
        case "105": assertEquals(puc.getReportedAmount(), 410.0); break;
        case "106": assertEquals(puc.getReportedAmount(), 411.0); break;
 
        case "100": assertEquals(puc.getReportedAmount(), 419.0); break;
        case "101": assertEquals(puc.getReportedAmount(), 420.0); break;
        case "102": assertEquals(puc.getReportedAmount(), 421.0); break;
        case "103": assertEquals(puc.getReportedAmount(), 422.0); break;
        case "111": assertEquals(puc.getReportedAmount(), 423.0); break;
        case "112": assertEquals(puc.getReportedAmount(), 424.0); break;
        case "113": assertEquals(puc.getReportedAmount(), 425.0); break;
        case "114": assertEquals(puc.getReportedAmount(), 426.0); break;
        case "115": assertEquals(puc.getReportedAmount(), 427.0); break;
        case "117": assertEquals(puc.getReportedAmount(), 428.0); break;
        case "118": assertEquals(puc.getReportedAmount(), 429.0); break;
        case "122": assertEquals(puc.getReportedAmount(), 430.0); break;
        case "126": assertEquals(puc.getReportedAmount(), 431.0); break;
        case "127": assertEquals(puc.getReportedAmount(), 432.0); break;
        case "128": assertEquals(puc.getReportedAmount(), 433.0); break;
        case "129": assertEquals(puc.getReportedAmount(), 434.0); break;
        case "130": assertEquals(puc.getReportedAmount(), 435.0); break;
        case "132": assertEquals(puc.getReportedAmount(), 436.0); break;
        case "136": assertEquals(puc.getReportedAmount(), 437.0); break;
        case "138": assertEquals(puc.getReportedAmount(), 438.0); break;
        case "149": assertEquals(puc.getReportedAmount(), 439.0); break;
        case "150": assertEquals(puc.getReportedAmount(), 440.0); break;
        case "151": assertEquals(puc.getReportedAmount(), 441.0); break;
        case "152": assertEquals(puc.getReportedAmount(), 442.0); break;
        case "166": assertEquals(puc.getReportedAmount(), 443.0); break;
        case "167": assertEquals(puc.getReportedAmount(), 444.0); break;
        case "178": assertEquals(puc.getReportedAmount(), 445.0); break;
        case "191": assertEquals(puc.getReportedAmount(), 446.0); break;
        case "192": assertEquals(puc.getReportedAmount(), 447.0); break;
        case "193": assertEquals(puc.getReportedAmount(), 448.0); break;
        case "194": assertEquals(puc.getReportedAmount(), 449.0); break;
        case "195": assertEquals(puc.getReportedAmount(), 450.0); break;
        case "196": assertEquals(puc.getReportedAmount(), 451.0); break;
      }
 
      assertEquals(data.getLayersEggsForHatching_108(), 412.0);
      assertEquals(data.getLayersEggsForConsumption_109(), 413.0);
      assertEquals(data.getBroilersChickens_143(), 414.0);
      assertEquals(data.getBroilersTurkeys_144(), 415.0);
 
      assertEquals(data.getProductiveCapacityLC123(), 416.0);
      assertEquals(data.getFeederHogsFedOver50Lbs_124(), 417.0);
      assertEquals(data.getFeederHogsFedUpTo50Lbs_125(), 418.0);
    }
  }


  protected SubmissionParentResource<NppSubmissionDataResource> buildSubmissionMetaData() {

    SubmissionParentResource<NppSubmissionDataResource> submissionMetaData = new SubmissionParentResource<>();
    submissionMetaData.setDeleted(false);
    submissionMetaData.setDraft(false);

    SubmissionResource<NppSubmissionDataResource> submission = new SubmissionResource<>();
    submissionMetaData.setSubmission(submission);

    NppSubmissionDataResource data = new NppSubmissionDataResource();
    submission.setData(data);

    return submissionMetaData;
  }


  protected SubmissionParentResource<NppSubmissionDataResource> loadSubmissionMetaDataFromJsonFile(String fileName) throws ServiceException {
    String submissionWrapperString = TestUtils.loadFileAsString(fileName);

    ObjectMapper jsonObjectMapper = new ObjectMapper();
    jsonObjectMapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
    
    JavaType parametricType = jsonObjectMapper.getTypeFactory().constructParametricType(SubmissionWrapperResource.class,
        NppSubmissionDataResource.class);
    
    SubmissionWrapperResource<NppSubmissionDataResource> submissionWrapper = chefsApiDao.parseResource(submissionWrapperString, parametricType);
    
    SubmissionParentResource<NppSubmissionDataResource> submissionMetaData = submissionWrapper.getSubmissionMetaData();
    return submissionMetaData;
  }


  @Override
  protected String getChefsFormType() {
    return CHEFS_FORM_TYPE;
  }

}
