create or replace procedure farms_enrolment_write_pkg.upsert_operational(
    in in_agristability_client_id farms.farm_program_enrolments.agristability_client_id%type,
    in in_enrolment_year farms.farm_program_enrolments.enrolment_year%type,
    in in_enrolment_fee farms.farm_program_enrolments.enrolment_fee%type,
    in in_failed_to_generate_ind farms.farm_program_enrolments.failed_to_generate_ind%type,
    in in_generated_from_cra_ind farms.farm_program_enrolments.generated_from_cra_ind%type,
    in in_generated_from_enw_ind farms.farm_program_enrolments.generated_from_enw_ind%type,
    in in_failed_reason farms.farm_program_enrolments.failed_reason%type,
    in in_generated_date farms.farm_program_enrolments.generated_date%type,
    in in_contribution_margin_average farms.farm_program_enrolments.contribution_margin_average%type,
    in in_margin_year_minus_2 farms.farm_program_enrolments.margin_year_minus_2%type,
    in in_margin_year_minus_3 farms.farm_program_enrolments.margin_year_minus_3%type,
    in in_margin_year_minus_4 farms.farm_program_enrolments.margin_year_minus_4%type,
    in in_margin_year_minus_5 farms.farm_program_enrolments.margin_year_minus_5%type,
    in in_margin_year_minus_6 farms.farm_program_enrolments.margin_year_minus_6%type,
    in in_margin_year_minus_2_ind farms.farm_program_enrolments.margin_year_minus_2_ind%type,
    in in_margin_year_minus_3_ind farms.farm_program_enrolments.margin_year_minus_3_ind%type,
    in in_margin_year_minus_4_ind farms.farm_program_enrolments.margin_year_minus_4_ind%type,
    in in_margin_year_minus_5_ind farms.farm_program_enrolments.margin_year_minus_5_ind%type,
    in in_margin_year_minus_6_ind farms.farm_program_enrolments.margin_year_minus_6_ind%type,
    in in_create_task_in_barn_ind farms.farm_program_enrolments.create_task_in_barn_ind%type,
    in in_combined_farm_percent farms.farm_program_enrolments.combined_farm_percent%type,
    in in_agristability_scenario_id farms.farm_program_enrolments.agristability_scenario_id%type,
    in in_user farms.farm_program_enrolments.who_updated%type
)
language plpgsql
as
$$
begin

    merge into farms.farm_program_enrolments pe
    using (
        select in_agristability_client_id agristability_client_id,
               in_enrolment_year enrolment_year,
               in_enrolment_fee enrolment_fee,
               in_failed_to_generate_ind failed_to_generate_ind,
               in_failed_reason failed_reason,
               in_generated_date generated_date,
               in_generated_from_cra_ind generated_from_cra_ind,
               in_generated_from_enw_ind generated_from_enw_ind,
               in_contribution_margin_average contribution_margin_average,
               in_margin_year_minus_2 margin_year_minus_2,
               in_margin_year_minus_3 margin_year_minus_3,
               in_margin_year_minus_4 margin_year_minus_4,
               in_margin_year_minus_5 margin_year_minus_5,
               in_margin_year_minus_6 margin_year_minus_6,
               in_margin_year_minus_2_ind margin_year_minus_2_ind,
               in_margin_year_minus_3_ind margin_year_minus_3_ind,
               in_margin_year_minus_4_ind margin_year_minus_4_ind,
               in_margin_year_minus_5_ind margin_year_minus_5_ind,
               in_margin_year_minus_6_ind margin_year_minus_6_ind,
               in_create_task_in_barn_ind create_task_in_barn_ind,
               in_combined_farm_percent combined_farm_percent,
               in_agristability_scenario_id agristability_scenario_id,
               in_user who_created,
               in_user who_updated
    ) x
    on x.agristability_client_id = pe.agristability_client_id
    and x.enrolment_year = pe.enrolment_year
    when matched then
        update set
        enrolment_fee = x.enrolment_fee,
        failed_to_generate_ind = x.failed_to_generate_ind,
        failed_reason = x.failed_reason,
        generated_date = x.generated_date,
        contribution_margin_average = x.contribution_margin_average,
        margin_year_minus_2 = x.margin_year_minus_2,
        margin_year_minus_3 = x.margin_year_minus_3,
        margin_year_minus_4 = x.margin_year_minus_4,
        margin_year_minus_5 = x.margin_year_minus_5,
        margin_year_minus_6 = x.margin_year_minus_6,
        margin_year_minus_2_ind = x.margin_year_minus_2_ind,
        margin_year_minus_3_ind = x.margin_year_minus_3_ind,
        margin_year_minus_4_ind = x.margin_year_minus_4_ind,
        margin_year_minus_5_ind = x.margin_year_minus_5_ind,
        margin_year_minus_6_ind = x.margin_year_minus_6_ind,
        generated_from_cra_ind = x.generated_from_cra_ind,
        generated_from_enw_ind = x.generated_from_enw_ind,
        create_task_in_barn_ind = x.create_task_in_barn_ind,
        combined_farm_percent = x.combined_farm_percent,
        agristability_scenario_id = x.agristability_scenario_id,
        revision_count = revision_count + 1,
        who_updated = x.who_updated,
        when_updated = current_timestamp
    when not matched then
        insert (
            program_enrolment_id,
            enrolment_year,
            enrolment_fee,
            failed_to_generate_ind,
            failed_reason,
            generated_date,
            contribution_margin_average,
            margin_year_minus_2,
            margin_year_minus_3,
            margin_year_minus_4,
            margin_year_minus_5,
            margin_year_minus_6,
            margin_year_minus_2_ind,
            margin_year_minus_3_ind,
            margin_year_minus_4_ind,
            margin_year_minus_5_ind,
            margin_year_minus_6_ind,
            generated_from_cra_ind,
            generated_from_enw_ind,
            create_task_in_barn_ind,
            combined_farm_percent,
            agristability_client_id,
            agristability_scenario_id,
            revision_count,
            who_created,
            when_created,
            who_updated,
            when_updated
        ) values (
            nextval('farms.farm_pgre_seq'),
            x.enrolment_year,
            x.enrolment_fee,
            x.failed_to_generate_ind,
            x.failed_reason,
            x.generated_date,
            x.contribution_margin_average,
            x.margin_year_minus_2,
            x.margin_year_minus_3,
            x.margin_year_minus_4,
            x.margin_year_minus_5,
            x.margin_year_minus_6,
            x.margin_year_minus_2_ind,
            x.margin_year_minus_3_ind,
            x.margin_year_minus_4_ind,
            x.margin_year_minus_5_ind,
            x.margin_year_minus_6_ind,
            x.generated_from_cra_ind,
            x.generated_from_enw_ind,
            x.create_task_in_barn_ind,
            x.combined_farm_percent,
            x.agristability_client_id,
            x.agristability_scenario_id,
            1,
            x.who_created,
            current_timestamp,
            x.who_updated,
            current_timestamp
        );

end;
$$;
