create or replace procedure farms_reasonability_write_pkg.update_reasonability_tests(
    inout in_reasonability_test_reslt_id farms.farm_reasonabilty_test_results.reasonability_test_result_id%type,
    in in_fresh_ind farms.farm_reasonabilty_test_results.fresh_ind%type,
    in in_forage_consumer_capacity farms.farm_reasonabilty_test_results.forage_consumer_capacity%type,
    in in_benefit_risk_pass_ind farms.farm_reasonabilty_test_results.benefit_risk_pass_ind%type,
    in in_program_year_margin farms.farm_reasonabilty_test_results.program_year_margin%type,
    in in_total_benefit farms.farm_reasonabilty_test_results.total_benefit%type,
    in in_benchmark_margin farms.farm_reasonabilty_test_results.benchmark_margin%type,
    in in_benchmark_margin_deductible farms.farm_reasonabilty_test_results.benchmark_margin_deductible%type,
    in in_benchmark_margin_less_ddctb farms.farm_reasonabilty_test_results.benchmark_margin_less_deductbl%type,
    in in_benchmark_margin_less_py_mg farms.farm_reasonabilty_test_results.benchmark_margin_less_py_marg%type,
    in in_benchmark_margin_payout_lvl farms.farm_reasonabilty_test_results.benchmark_margin_payout_level%type,
    in in_benefit_benchmark_bfr_cmbnd farms.farm_reasonabilty_test_results.benefit_benchmark_befor_combnd%type,
    in in_combined_benefit_percent farms.farm_reasonabilty_test_results.combined_benefit_percent%type,
    in in_benefit_benchmark farms.farm_reasonabilty_test_results.benefit_benchmark%type,
    in in_benefit_risk_variance farms.farm_reasonabilty_test_results.benefit_risk_variance%type,
    in in_benefit_risk_variance_limit farms.farm_reasonabilty_test_results.benefit_risk_variance_limit%type,
    in in_margin_pass_ind farms.farm_reasonabilty_test_results.margin_pass_ind%type,
    in in_adjusted_reference_margin farms.farm_reasonabilty_test_results.adjusted_reference_margin%type,
    in in_adj_reference_margin_vrince farms.farm_reasonabilty_test_results.adj_reference_margin_variance%type,
    in in_adj_refernce_mrgn_vrinc_lmt farms.farm_reasonabilty_test_results.adj_reference_margin_vrinc_lmt%type,
    in in_within_lmt_pct_ref_mrgn_ind farms.farm_reasonabilty_test_results.within_lmt_prct_ref_margin_ind%type,
    in in_margin_industry_average farms.farm_reasonabilty_test_results.margin_industry_average%type,
    in in_margin_industry_avg_varianc farms.farm_reasonabilty_test_results.margin_industry_avg_variance%type,
    in in_margin_industry_avg_limit farms.farm_reasonabilty_test_results.margin_industry_average_limit%type,
    in in_margin_wthn_lmt_ind_avg_ind farms.farm_reasonabilty_test_results.margin_wthn_lmt_indtry_avg_ind%type,
    in in_structural_change_pass_ind farms.farm_reasonabilty_test_results.structural_change_pass_ind%type,
    in in_production_marg_accr_adjs farms.farm_reasonabilty_test_results.production_marg_accr_adjs%type,
    in in_ratio_adj_reference_margin farms.farm_reasonabilty_test_results.ratio_adj_reference_margin%type,
    in in_additive_adj_reference_marg farms.farm_reasonabilty_test_results.additive_adj_reference_margin%type,
    in in_ratio_additiv_ref_marg_diff farms.farm_reasonabilty_test_results.ratio_additive_ref_marg_diff%type,
    in in_ratio_add_diff_dollar_limit farms.farm_reasonabilty_test_results.ratio_add_diff_dollar_limit%type,
    in in_within_dlr_lmt_rtio_add_ind farms.farm_reasonabilty_test_results.within_dlr_limit_ratio_add_ind%type,
    in in_additive_division_ratio farms.farm_reasonabilty_test_results.additive_division_ratio%type,
    in in_additive_divisn_ratio_limit farms.farm_reasonabilty_test_results.additive_division_ratio_limit%type,
    in in_within_limit_addtiv_div_ind farms.farm_reasonabilty_test_results.within_limit_addtiv_divisn_ind%type,
    in in_structual_chg_method_to_use farms.farm_reasonabilty_test_results.structual_change_method_to_use%type,
    in in_farm_size_ratio_limit farms.farm_reasonabilty_test_results.farm_size_ratio_limit%type,
    in in_farm_siz_rtios_wthn_lmt_ind farms.farm_reasonabilty_test_results.farm_size_rtios_within_lmt_ind%type,
    in in_expense_ind_av_cmp_pass_ind farms.farm_reasonabilty_test_results.expense_indtry_av_cmp_pass_ind%type,
    in in_expense_accr_adjs_indtry_av farms.farm_reasonabilty_test_results.expense_accr_adjs_indtry_av_cm%type,
    in in_expense_industry_average farms.farm_reasonabilty_test_results.expense_industry_average%type,
    in in_expense_industry_avg_vrianc farms.farm_reasonabilty_test_results.expense_industry_avg_variance%type,
    in in_expense_industry_avg_limit farms.farm_reasonabilty_test_results.expense_industry_average_limit%type,
    in in_agristability_scenario_id farms.farm_reasonabilty_test_results.agristability_scenario_id%type,
    in in_prod_pass_ind farms.farm_reasonabilty_test_results.production_pass_ind%type,
    in in_prod_forage_fs_pass_ind farms.farm_reasonabilty_test_results.production_forage_fs_pass_ind%type,
    in in_fruit_veg_pass_ind farms.farm_reasonabilty_test_results.production_fruit_veg_pass_ind%type,
    in in_prod_forage_qty_limit farms.farm_reasonabilty_test_results.prod_forage_qty_produced_limit%type,
    in in_prod_fruit_veg_qty_limit farms.farm_reasonabilty_test_results.prod_fruit_veg_qty_prodcd_limt%type,
    in in_prod_grain_qty_limit farms.farm_reasonabilty_test_results.prod_grain_qty_produced_limit%type,
    in in_prod_grain_pass_ind farms.farm_reasonabilty_test_results.production_grains_pass_ind%type,
    in in_expense_rf_yr_comp_pass_ind farms.farm_reasonabilty_test_results.expense_ref_year_comp_pass_ind%type,
    in in_expense_accr_adjs farms.farm_reasonabilty_test_results.expense_accr_adjs%type,
    in in_expense_aft_str_ch_yr_mn_1 farms.farm_reasonabilty_test_results.expenses_aft_str_ch_yr_minus_1%type,
    in in_expense_aft_str_ch_yr_mn_2 farms.farm_reasonabilty_test_results.expenses_aft_str_ch_yr_minus_2%type,
    in in_expense_aft_str_ch_yr_mn_3 farms.farm_reasonabilty_test_results.expenses_aft_str_ch_yr_minus_3%type,
    in in_expense_aft_str_ch_yr_mn_4 farms.farm_reasonabilty_test_results.expenses_aft_str_ch_yr_minus_4%type,
    in in_expense_aft_str_ch_yr_mn_5 farms.farm_reasonabilty_test_results.expenses_aft_str_ch_yr_minus_5%type,
    in in_expense_aft_st_ch_rf_yr_avg farms.farm_reasonabilty_test_results.expenses_aft_str_ch_ref_yr_avg%type,
    in in_expense_aft_str_ch_variance farms.farm_reasonabilty_test_results.expenses_aft_str_ch_variance%type,
    in in_expense_aft_str_ch_vrn_lmt farms.farm_reasonabilty_test_results.expenses_aft_str_ch_varian_lmt%type,
    in in_rev_rsk_grain_frg_pass_ind farms.farm_reasonabilty_test_results.revenue_rsk_grain_frg_pass_ind%type,
    in in_rev_risk_pass_ind farms.farm_reasonabilty_test_results.revenue_risk_pass_ind%type,
    in in_rev_risk_grain_forage_limit farms.farm_reasonabilty_test_results.revenue_rsk_grain_forage_limit%type,
    in in_rev_risk_fruit_vegin_ind farms.farm_reasonabilty_test_results.revenue_risk_fruit_vg_pass_ind%type,
    in in_user farms.farm_reasonabilty_test_results.who_updated%type
)
language plpgsql
as
$$
begin

    if coalesce(in_reasonability_test_reslt_id::text, '') = '' then

        insert into farms.farm_reasonabilty_test_results (
            reasonability_test_result_id,
            fresh_ind,
            generated_date,
            forage_consumer_capacity,
            benefit_risk_pass_ind,
            program_year_margin,
            total_benefit,
            benchmark_margin,
            benchmark_margin_deductible,
            benchmark_margin_less_deductbl,
            benchmark_margin_less_py_marg,
            benchmark_margin_payout_level,
            benefit_benchmark_befor_combnd,
            combined_benefit_percent,
            benefit_benchmark,
            benefit_risk_variance,
            benefit_risk_variance_limit,
            margin_pass_ind,
            adjusted_reference_margin,
            adj_reference_margin_variance,
            adj_reference_margin_vrinc_lmt,
            within_lmt_prct_ref_margin_ind,
            margin_industry_average,
            margin_industry_avg_variance,
            margin_industry_average_limit,
            margin_wthn_lmt_indtry_avg_ind,
            structural_change_pass_ind,
            production_marg_accr_adjs,
            ratio_adj_reference_margin,
            additive_adj_reference_margin,
            ratio_additive_ref_marg_diff,
            ratio_add_diff_dollar_limit,
            within_dlr_limit_ratio_add_ind,
            additive_division_ratio,
            additive_division_ratio_limit,
            within_limit_addtiv_divisn_ind,
            structual_change_method_to_use,
            farm_size_ratio_limit,
            farm_size_rtios_within_lmt_ind,
            expense_indtry_av_cmp_pass_ind,
            expense_accr_adjs_indtry_av_cm,
            expense_industry_average,
            expense_industry_avg_variance,
            expense_industry_average_limit,
            production_pass_ind,
            production_forage_fs_pass_ind,
            production_fruit_veg_pass_ind,
            agristability_scenario_id,
            prod_forage_qty_produced_limit,
            prod_fruit_veg_qty_prodcd_limt,
            prod_grain_qty_produced_limit,
            production_grains_pass_ind,
            expense_ref_year_comp_pass_ind,
            expense_accr_adjs,
            expenses_aft_str_ch_yr_minus_1,
            expenses_aft_str_ch_yr_minus_2,
            expenses_aft_str_ch_yr_minus_3,
            expenses_aft_str_ch_yr_minus_4,
            expenses_aft_str_ch_yr_minus_5,
            expenses_aft_str_ch_ref_yr_avg,
            expenses_aft_str_ch_variance,
            expenses_aft_str_ch_varian_lmt,
            revenue_rsk_grain_frg_pass_ind,
            revenue_risk_pass_ind,
            revenue_rsk_grain_forage_limit,
            revenue_risk_fruit_vg_pass_ind,
            revision_count,
            who_created,
            when_created,
            who_updated,
            when_updated
        ) values (
            nextval('farms.farm_rtr_seq'),
            in_fresh_ind,
            current_timestamp,
            in_forage_consumer_capacity,
            in_benefit_risk_pass_ind,
            in_program_year_margin,
            in_total_benefit,
            in_benchmark_margin,
            in_benchmark_margin_deductible,
            in_benchmark_margin_less_ddctb,
            in_benchmark_margin_less_py_mg,
            in_benchmark_margin_payout_lvl,
            in_benefit_benchmark_bfr_cmbnd,
            in_combined_benefit_percent,
            in_benefit_benchmark,
            in_benefit_risk_variance,
            in_benefit_risk_variance_limit,
            in_margin_pass_ind,
            in_adjusted_reference_margin,
            in_adj_reference_margin_vrince,
            in_adj_refernce_mrgn_vrinc_lmt,
            in_within_lmt_pct_ref_mrgn_ind,
            in_margin_industry_average,
            in_margin_industry_avg_varianc,
            in_margin_industry_avg_limit,
            in_margin_wthn_lmt_ind_avg_ind,
            in_structural_change_pass_ind,
            in_production_marg_accr_adjs,
            in_ratio_adj_reference_margin,
            in_additive_adj_reference_marg,
            in_ratio_additiv_ref_marg_diff,
            in_ratio_add_diff_dollar_limit,
            in_within_dlr_lmt_rtio_add_ind,
            in_additive_division_ratio,
            in_additive_divisn_ratio_limit,
            in_within_limit_addtiv_div_ind,
            in_structual_chg_method_to_use,
            in_farm_size_ratio_limit,
            in_farm_siz_rtios_wthn_lmt_ind,
            in_expense_ind_av_cmp_pass_ind,
            in_expense_accr_adjs_indtry_av,
            in_expense_industry_average,
            in_expense_industry_avg_vrianc,
            in_expense_industry_avg_limit,
            in_prod_pass_ind,
            in_prod_forage_fs_pass_ind,
            in_fruit_veg_pass_ind,
            in_agristability_scenario_id,
            in_prod_forage_qty_limit,
            in_prod_fruit_veg_qty_limit,
            in_prod_grain_qty_limit,
            in_prod_grain_pass_ind,
            in_expense_rf_yr_comp_pass_ind,
            in_expense_accr_adjs,
            in_expense_aft_str_ch_yr_mn_1,
            in_expense_aft_str_ch_yr_mn_2,
            in_expense_aft_str_ch_yr_mn_3,
            in_expense_aft_str_ch_yr_mn_4,
            in_expense_aft_str_ch_yr_mn_5,
            in_expense_aft_st_ch_rf_yr_avg,
            in_expense_aft_str_ch_variance,
            in_expense_aft_str_ch_vrn_lmt,
            in_rev_rsk_grain_frg_pass_ind,
            in_rev_risk_pass_ind,
            in_rev_risk_grain_forage_limit,
            in_rev_risk_fruit_vegin_ind,
            1,
            in_user,
            current_timestamp,
            in_user,
            current_timestamp
        ) returning reasonability_test_result_id into in_reasonability_test_reslt_id;

    else

        update farms.farm_reasonabilty_test_results
        set fresh_ind = in_fresh_ind,
            generated_date = current_timestamp,

            forage_consumer_capacity = in_forage_consumer_capacity,
            benefit_risk_pass_ind = in_benefit_risk_pass_ind,
            program_year_margin = in_program_year_margin,
            total_benefit = in_total_benefit,
            benchmark_margin = in_benchmark_margin,
            benchmark_margin_deductible = in_benchmark_margin_deductible,
            benchmark_margin_less_deductbl = in_benchmark_margin_less_ddctb,
            benchmark_margin_less_py_marg = in_benchmark_margin_less_py_mg,
            benchmark_margin_payout_level = in_benchmark_margin_payout_lvl,
            benefit_benchmark_befor_combnd = in_benefit_benchmark_bfr_cmbnd,
            combined_benefit_percent = in_combined_benefit_percent,
            benefit_benchmark = in_benefit_benchmark,
            benefit_risk_variance = in_benefit_risk_variance,
            benefit_risk_variance_limit = in_benefit_risk_variance_limit,

            margin_pass_ind = in_margin_pass_ind,
            adjusted_reference_margin = in_adjusted_reference_margin,
            adj_reference_margin_variance = in_adj_reference_margin_vrince,
            adj_reference_margin_vrinc_lmt = in_adj_refernce_mrgn_vrinc_lmt,
            within_lmt_prct_ref_margin_ind = in_within_lmt_pct_ref_mrgn_ind,
            margin_industry_average = in_margin_industry_average,
            margin_industry_avg_variance = in_margin_industry_avg_varianc,
            margin_industry_average_limit = in_margin_industry_avg_limit,
            margin_wthn_lmt_indtry_avg_ind = in_margin_wthn_lmt_ind_avg_ind,

            structural_change_pass_ind = in_structural_change_pass_ind,
            production_marg_accr_adjs = in_production_marg_accr_adjs,
            ratio_adj_reference_margin = in_ratio_adj_reference_margin,
            additive_adj_reference_margin = in_additive_adj_reference_marg,
            ratio_additive_ref_marg_diff = in_ratio_additiv_ref_marg_diff,
            ratio_add_diff_dollar_limit = in_ratio_add_diff_dollar_limit,
            within_dlr_limit_ratio_add_ind = in_within_dlr_lmt_rtio_add_ind,
            additive_division_ratio = in_additive_division_ratio,
            additive_division_ratio_limit = in_additive_divisn_ratio_limit,
            within_limit_addtiv_divisn_ind = in_within_limit_addtiv_div_ind,
            structual_change_method_to_use = in_structual_chg_method_to_use,
            farm_size_ratio_limit = in_farm_size_ratio_limit,
            farm_size_rtios_within_lmt_ind = in_farm_siz_rtios_wthn_lmt_ind,

            expense_indtry_av_cmp_pass_ind = in_expense_ind_av_cmp_pass_ind,
            expense_accr_adjs_indtry_av_cm = in_expense_accr_adjs_indtry_av,
            expense_industry_average = in_expense_industry_average,
            expense_industry_avg_variance = in_expense_industry_avg_vrianc,
            expense_industry_average_limit = in_expense_industry_avg_limit,

            production_pass_ind = in_prod_pass_ind,
            production_forage_fs_pass_ind = in_prod_forage_fs_pass_ind,
            production_fruit_veg_pass_ind = in_fruit_veg_pass_ind,
            prod_forage_qty_produced_limit = in_prod_forage_qty_limit,
            prod_fruit_veg_qty_prodcd_limt = in_prod_fruit_veg_qty_limit,
            production_grains_pass_ind = in_prod_grain_pass_ind,
            prod_grain_qty_produced_limit = in_prod_grain_qty_limit,

            expense_ref_year_comp_pass_ind = in_expense_rf_yr_comp_pass_ind,
            expense_accr_adjs = in_expense_accr_adjs,
            expenses_aft_str_ch_yr_minus_1 = in_expense_aft_str_ch_yr_mn_1,
            expenses_aft_str_ch_yr_minus_2 = in_expense_aft_str_ch_yr_mn_2,
            expenses_aft_str_ch_yr_minus_3 = in_expense_aft_str_ch_yr_mn_3,
            expenses_aft_str_ch_yr_minus_4 = in_expense_aft_str_ch_yr_mn_4,
            expenses_aft_str_ch_yr_minus_5 = in_expense_aft_str_ch_yr_mn_5,
            expenses_aft_str_ch_ref_yr_avg = in_expense_aft_st_ch_rf_yr_avg,
            expenses_aft_str_ch_variance = in_expense_aft_str_ch_variance,
            expenses_aft_str_ch_varian_lmt = in_expense_aft_str_ch_vrn_lmt,

            revenue_rsk_grain_frg_pass_ind = in_rev_rsk_grain_frg_pass_ind,
            revenue_risk_pass_ind = in_rev_risk_pass_ind,
            revenue_rsk_grain_forage_limit = in_rev_risk_grain_forage_limit,
            revenue_risk_fruit_vg_pass_ind = in_rev_risk_fruit_vegin_ind,

            revision_count = revision_count + 1,
            who_updated = in_user,
            when_updated = current_timestamp
        where reasonability_test_result_id = in_reasonability_test_reslt_id;

    end if;

end;
$$;
