-- schema
GRANT ALL ON SCHEMA "farms" TO "app_farms";
GRANT ALL ON SCHEMA "farms" TO postgres;
GRANT USAGE ON SCHEMA "farms" TO "app_farms_rest_proxy";

-- tables
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_aarm_margins TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_agristability_claims TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_agristability_clients TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_agristability_represntves TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_agristability_scenarios TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_agristabilty_cmmdty_xref TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_benchmark_per_units TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_benchmark_years TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_benefit_calc_documents TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_benefit_calc_margins TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_benefit_calc_totals TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_chef_form_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_chef_submissions TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_chef_submssn_crm_entities TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_chef_submssn_status_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_client_subscriptions TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_commodity_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_config_param_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_configuration_parameters TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_crm_entity_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_crop_unit_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_crop_unit_conversn_fctrs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_crop_unit_defaults TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_document_templates TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_enrolment_calc_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_expected_productions TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_fair_market_values TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_farm_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_farming_operatin_prtnrs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_farming_operations TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_federal_accounting_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_federal_status_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_fruit_veg_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_fruit_veg_type_details TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_import_class_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_import_logs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_import_state_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_import_versions TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_inventory_class_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_inventory_group_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_inventory_item_attributes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_inventory_item_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_inventory_item_details TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_line_items TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_market_rate_premium TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_message_type_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_multi_stage_commdty_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_municipality_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_negative_margins TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_office_municipality_xref TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_participant_class_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_participant_lang_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_participant_profile_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_participnt_data_src_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_persons TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_production_insurances TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_productve_unit_capacities TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_program_enrolments TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_program_year_versions TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_program_years TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_reasonabilty_test_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_reference_scenarios TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_regional_office_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_reported_income_expenses TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_reported_inventories TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_bnft_rsk_prd_un_rslts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_forage_consumers TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_prdctn_forage_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_prdctn_frut_invntries TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_prdctn_frut_veg_rslts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_prdctn_grain_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_result_messages TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_fruit_veg_invntrs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_fruit_veg_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_g_f_fs_incm_rslts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_g_f_fs_invntories TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_hog_inventories TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_hog_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_nursery_incomes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_nursery_invntries TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_nursery_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_poultry_brl_rslts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_rsn_rev_poultry_egg_rslts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_bpu_purpos_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_bpu_xref TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_category_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_class_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_config_params TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_enrolments TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_logs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_state_audits TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_scenario_state_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_sector_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_sector_detail_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_sector_detail_line_items TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_sector_detail_xref TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_structural_change_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_structure_group_attributs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_structure_group_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_subscription_status_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_benchmark_expenses TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_benchmark_years TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_farm_type_1_lookups TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_farm_type_2_lookups TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_farm_type_3_lookups TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_income_ranges TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_line_items TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_rating_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_report_documents TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_report_expenses TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_tip_report_results TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_triage_queue_codes TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_users TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_whole_farm_participants TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_year_configuration_params TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z01_participant_infos TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z02_partpnt_farm_infos TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z03_statement_infos TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z04_income_exps_dtls TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z05_partner_infos TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z21_participant_suppls TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z22_production_insurances TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z23_livestock_prod_cpcts TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z28_prod_insurance_refs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z29_inventory_code_refs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z40_prtcpnt_ref_supl_dtls TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z42_participant_ref_years TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z50_participnt_bnft_calcs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z51_participant_contribs TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_z99_extract_file_ctls TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_zaarm_margins TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_zbpu_benchmark_per_units TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_zfmv_fair_market_values TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_zivpr_iv_premium_rates TO "app_farms_rest_proxy";
GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_zprogram_enrolments TO "app_farms_rest_proxy";

-- tables (truncate)
GRANT TRUNCATE ON TABLE farms.farm_zbpu_benchmark_per_units TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_zfmv_fair_market_values TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_zivpr_iv_premium_rates TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_import_logs TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z99_extract_file_ctls TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z51_participant_contribs TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z50_participnt_bnft_calcs TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z42_participant_ref_years TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z40_prtcpnt_ref_supl_dtls TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z23_livestock_prod_cpcts TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z22_production_insurances TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z21_participant_suppls TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z28_prod_insurance_refs TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z29_inventory_code_refs TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z05_partner_infos TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z04_income_exps_dtls TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z03_statement_infos TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z02_partpnt_farm_infos TO "app_farms_rest_proxy";
GRANT TRUNCATE ON TABLE farms.farm_z01_participant_infos TO "app_farms_rest_proxy";

-- views
GRANT SELECT ON farms.farm_agri_scenarios_vw TO "app_farms_rest_proxy";
GRANT SELECT ON farms.farm_chef_statement_a_years_vw TO "app_farms_rest_proxy";
GRANT SELECT ON farms.farm_operations_vw TO "app_farms_rest_proxy";
GRANT SELECT ON farms.farm_scenarios_vw TO "app_farms_rest_proxy";

-- sequences
GRANT USAGE ON SEQUENCE farms.farm_acl_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_acx_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_asc_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_asr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_as_cfn_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_as_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_bcd_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_bcmt_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_bcm_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_bpux_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_bpu_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_cp_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_csce_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_csub_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_cs_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_cucf_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_cud_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_dt_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_ep_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_fmv_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_fop_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_fo_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_fvtd_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_iia_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_iid_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_ilg_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_iv_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_li_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_mrp_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_nm_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_omx_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_per_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_pgre_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_pi_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_puc_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_pyc_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_pyv_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_py_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rbrpu_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rfc_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rie_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_ri_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rpfi_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rpfr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rpfvr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rpgr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrfvi_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrfvr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrgir_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrgi_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrhi_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrhr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrm_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrnir_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrni_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrnr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrpbr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rrpe_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rs_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_rtr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_scp_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_sdli_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_sdx_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_se_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_sga_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_sl_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_ssa_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tbe_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tby_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tft1l_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tft2l_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tft3l_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tir_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tli_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_trd_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_tre_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_trr_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_u_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_wfp_seq TO "app_farms_rest_proxy";
GRANT USAGE ON SEQUENCE farms.farm_ycp_seq TO "app_farms_rest_proxy";
