CREATE TABLE farms.farm_urls (
    url_id bigint NOT NULL,
    url varchar(256) NOT NULL,
    revision_count integer NOT NULL DEFAULT 1,
    who_created varchar(30) NOT NULL,
    when_created timestamp(0) NOT NULL DEFAULT statement_timestamp(),
    who_updated varchar(30),
    when_updated timestamp(0) DEFAULT statement_timestamp()
) ;
COMMENT ON TABLE farms.farm_urls IS E'URLS Is to store the URL of the file in SharePoint Online.';
COMMENT ON COLUMN farms.farm_urls.url_id IS E'URL ID Is the Primary Key. A numeric ID generated by a sequence.';
COMMENT ON COLUMN farms.farm_urls.url IS E'URL Is a string, the URL of the file. Must have a Unique Key.';
COMMENT ON COLUMN farms.farm_urls.revision_count IS E'REVISION COUNT is a counter identifying the number of times this record as been modified. Used in the web page access to determine if the record as been modified since the data was first retrieved.';
COMMENT ON COLUMN farms.farm_urls.when_created IS E'WHEN CREATED indicates when the physical record was created in the database.';
COMMENT ON COLUMN farms.farm_urls.when_updated IS E'WHEN UPDATED indicates when the physical record was updated in the database.';
COMMENT ON COLUMN farms.farm_urls.who_created IS E'WHO CREATED indicates the user that created the physical record in the database.';
COMMENT ON COLUMN farms.farm_urls.who_updated IS E'WHO UPDATED indicates the user that updated the physical record in the database.';
ALTER TABLE farms.farm_urls ADD CONSTRAINT farm_url_as_uk UNIQUE (url);
ALTER TABLE farms.farm_urls ADD CONSTRAINT farm_url_pk PRIMARY KEY (url_id);

CREATE SEQUENCE farm_url_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1 CACHE 20;

GRANT SELECT, INSERT, UPDATE, DELETE ON farms.farm_urls TO "app_farms_rest_proxy";
