CREATE SEQUENCE farms.farm_acx_seq INCREMENT 1 MINVALUE 0 NO MAXVALUE START 233520 CACHE 20;
CREATE SEQUENCE farms.farm_bpu_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 60584 CACHE 20;
CREATE SEQUENCE farms.farm_fmv_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 730605 CACHE 20;
CREATE SEQUENCE farms.farm_iia_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 3961 CACHE 20;
CREATE SEQUENCE farms.farm_iid_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 55361 CACHE 20;
