create or replace procedure farms_reasonability_write_pkg.insert_farm_rsn_rev_hog_rslts(
    in in_reasonability_test_reslt_id farms.farm_rsn_rev_hog_results.reasonability_test_result_id%type,
    in in_has_hogs_ind farms.farm_rsn_rev_hog_results.has_hogs_ind%type,
    in in_hogs_pass_ind farms.farm_rsn_rev_hog_results.hogs_pass_ind%type,
    in in_farrow_to_finish_operation_ind farms.farm_rsn_rev_hog_results.farrow_to_finish_operation_ind%type,
    in in_feeder_operation_ind farms.farm_rsn_rev_hog_results.feeder_operation_ind%type,
    in in_reported_expenses farms.farm_rsn_rev_hog_results.reported_expenses%type,
    in in_total_quantity_start farms.farm_rsn_rev_hog_results.total_quantity_start%type,
    in in_total_quantity_end farms.farm_rsn_rev_hog_results.total_quantity_end%type,
    in in_farrow_sows_breeding farms.farm_rsn_rev_hog_results.farrow_sows_breeding%type,
    in in_farrow_births_per_cycle farms.farm_rsn_rev_hog_results.farrow_births_per_cycle%type,
    in in_farrow_birth_cycles_per_year farms.farm_rsn_rev_hog_results.farrow_birth_cycles_per_year%type,
    in in_farrow_total_births_per_cycle farms.farm_rsn_rev_hog_results.farrow_total_births_per_cycle%type,
    in in_farrow_births_all_cycles farms.farm_rsn_rev_hog_results.farrow_births_all_cycles%type,
    in in_farrow_death_rate farms.farm_rsn_rev_hog_results.farrow_death_rate%type,
    in in_farrow_deaths farms.farm_rsn_rev_hog_results.farrow_deaths%type,
    in in_farrow_boar_purchase_count farms.farm_rsn_rev_hog_results.farrow_boar_purchase_count%type,
    in in_farrow_boar_purchase_price farms.farm_rsn_rev_hog_results.farrow_boar_purchase_price%type,
    in in_farrow_boar_purchase_expense farms.farm_rsn_rev_hog_results.farrow_boar_purchase_expense%type,
    in in_farrow_sow_purchase_expense farms.farm_rsn_rev_hog_results.farrow_sow_purchase_expense%type,
    in in_farrow_sow_purchase_count farms.farm_rsn_rev_hog_results.farrow_sow_purchase_count%type,
    in in_farrow_sow_purchase_price farms.farm_rsn_rev_hog_results.farrow_sow_purchase_count%type,
    in in_feeder_productive_units farms.farm_rsn_rev_hog_results.feeder_productive_units%type,
    in in_feeder_weanling_purchase_expns farms.farm_rsn_rev_hog_results.feeder_weanling_purchase_expns%type,
    in in_feeder_weanling_purchase_price farms.farm_rsn_rev_hog_results.feeder_weanling_purchase_price%type,
    in in_feeder_weanling_purchase_count farms.farm_rsn_rev_hog_results.feeder_weanling_purchase_count%type,
    in in_total_purchase_count farms.farm_rsn_rev_hog_results.total_purchase_count%type,
    in in_expected_sold farms.farm_rsn_rev_hog_results.expected_sold%type,
    in in_heaviest_hog_price farms.farm_rsn_rev_hog_results.heaviest_hog_price%type,
    in in_reported_revenue farms.farm_rsn_rev_hog_results.reported_revenue%type,
    in in_expected_revenue farms.farm_rsn_rev_hog_results.expected_revenue%type,
    in in_revenue_variance farms.farm_rsn_rev_hog_results.revenue_variance%type,
    in in_revenue_variance_limit farms.farm_rsn_rev_hog_results.revenue_variance_limit%type,
    in in_user farms.farm_rsn_rev_hog_results.who_created%type
)
language plpgsql
as
$$
begin

    insert into farms.farm_rsn_rev_hog_results (
        rsn_rev_hog_result_id,
        has_hogs_ind,
        hogs_pass_ind,
        farrow_to_finish_operation_ind,
        feeder_operation_ind,
        reported_expenses,
        total_quantity_start,
        total_quantity_end,
        farrow_sows_breeding,
        farrow_births_per_cycle,
        farrow_birth_cycles_per_year,
        farrow_total_births_per_cycle,
        farrow_births_all_cycles,
        farrow_death_rate,
        farrow_deaths,
        farrow_boar_purchase_count,
        farrow_boar_purchase_price,
        farrow_boar_purchase_expense,
        farrow_sow_purchase_expense,
        farrow_sow_purchase_count,
        farrow_sow_purchase_price,
        feeder_productive_units,
        feeder_weanling_purchase_expns,
        feeder_weanling_purchase_price,
        feeder_weanling_purchase_count,
        total_purchase_count,
        expected_sold,
        heaviest_hog_price,
        reported_revenue,
        expected_revenue,
        revenue_variance,
        revenue_variance_limit,
        reasonability_test_result_id,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        nextval('farms.farm_rrhr_seq'),
        in_has_hogs_ind,
        in_hogs_pass_ind,
        in_farrow_to_finish_operation_ind,
        in_feeder_operation_ind,
        in_reported_expenses,
        in_total_quantity_start,
        in_total_quantity_end,
        in_farrow_sows_breeding,
        in_farrow_births_per_cycle,
        in_farrow_birth_cycles_per_year,
        in_farrow_total_births_per_cycle,
        in_farrow_births_all_cycles,
        in_farrow_death_rate,
        in_farrow_deaths,
        in_farrow_boar_purchase_count,
        in_farrow_boar_purchase_price,
        in_farrow_boar_purchase_expense,
        in_farrow_sow_purchase_expense,
        in_farrow_sow_purchase_count,
        in_farrow_sow_purchase_price,
        in_feeder_productive_units,
        in_feeder_weanling_purchase_expns,
        in_feeder_weanling_purchase_price,
        in_feeder_weanling_purchase_count,
        in_total_purchase_count,
        in_expected_sold,
        in_heaviest_hog_price,
        in_reported_revenue,
        in_expected_revenue,
        in_revenue_variance,
        in_revenue_variance_limit,
        in_reasonability_test_reslt_id,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );

end;
$$;
