create or replace procedure farms_reasonability_write_pkg.insert_farm_rsnblty_rev_egg_rslts(
    in in_reasonability_test_reslt_id farms.farm_rsn_rev_poultry_egg_rslts.reasonability_test_result_id%type,
    in in_has_poultry_eggs_ind farms.farm_rsn_rev_poultry_egg_rslts.has_poultry_eggs_ind%type,
    in in_poultry_eggs_pass_ind farms.farm_rsn_rev_poultry_egg_rslts.poultry_eggs_pass_ind%type,
    in in_consumption_pass_ind farms.farm_rsn_rev_poultry_egg_rslts.consumption_pass_ind%type,
    in in_consumption_layers farms.farm_rsn_rev_poultry_egg_rslts.consumption_layers%type,
    in in_consumption_avg_eggs_per_layer farms.farm_rsn_rev_poultry_egg_rslts.consumption_avg_eggs_per_layer%type,
    in in_consumption_eggs_total farms.farm_rsn_rev_poultry_egg_rslts.consumption_eggs_total%type,
    in in_consumption_eggs_dozen_sold farms.farm_rsn_rev_poultry_egg_rslts.consumption_eggs_dozen_sold%type,
    in in_consumption_price_per_dozen farms.farm_rsn_rev_poultry_egg_rslts.consumption_price_per_dozen%type,
    in in_consumption_expected_revenue farms.farm_rsn_rev_poultry_egg_rslts.consumption_expected_revenue%type,
    in in_consumption_reported_revenue farms.farm_rsn_rev_poultry_egg_rslts.consumption_reported_revenue%type,
    in in_consumption_revenue_variance farms.farm_rsn_rev_poultry_egg_rslts.consumption_revenue_variance%type,
    in in_consumption_revenue_varinc_lmt farms.farm_rsn_rev_poultry_egg_rslts.consumption_revenue_varinc_lmt%type,
    in in_hatching_pass_ind farms.farm_rsn_rev_poultry_egg_rslts.hatching_pass_ind%type,
    in in_hatching_layers farms.farm_rsn_rev_poultry_egg_rslts.hatching_layers%type,
    in in_hatching_avg_eggs_per_layer farms.farm_rsn_rev_poultry_egg_rslts.hatching_avg_eggs_per_layer%type,
    in in_hatching_eggs_total farms.farm_rsn_rev_poultry_egg_rslts.hatching_eggs_total%type,
    in in_hatching_eggs_dozen_sold farms.farm_rsn_rev_poultry_egg_rslts.hatching_eggs_dozen_sold%type,
    in in_hatching_price_per_dozen farms.farm_rsn_rev_poultry_egg_rslts.hatching_price_per_dozen%type,
    in in_hatching_expected_revenue farms.farm_rsn_rev_poultry_egg_rslts.hatching_expected_revenue%type,
    in in_hatching_reported_revenue farms.farm_rsn_rev_poultry_egg_rslts.hatching_reported_revenue%type,
    in in_hatching_revenue_variance farms.farm_rsn_rev_poultry_egg_rslts.hatching_revenue_variance%type,
    in in_hatching_revenue_variance_limt farms.farm_rsn_rev_poultry_egg_rslts.hatching_revenue_variance_limt%type,
    in in_user farms.farm_rsn_rev_poultry_egg_rslts.who_created%type
)
language plpgsql
as
$$
begin
    insert into farms.farm_rsn_rev_poultry_egg_rslts (
        rsn_rev_poultry_egg_rslt_id,
        poultry_eggs_pass_ind,
        has_poultry_eggs_ind,
        consumption_pass_ind,
        consumption_layers,
        consumption_avg_eggs_per_layer,
        consumption_eggs_total,
        consumption_eggs_dozen_sold,
        consumption_price_per_dozen,
        consumption_expected_revenue,
        consumption_reported_revenue,
        consumption_revenue_variance,
        consumption_revenue_varinc_lmt,
        hatching_pass_ind,
        hatching_layers,
        hatching_avg_eggs_per_layer,
        hatching_eggs_total,
        hatching_eggs_dozen_sold,
        hatching_price_per_dozen,
        hatching_expected_revenue,
        hatching_reported_revenue,
        hatching_revenue_variance,
        hatching_revenue_variance_limt,
        reasonability_test_result_id,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        nextval('farms.farm_rrpe_seq'),
        in_poultry_eggs_pass_ind,
        in_has_poultry_eggs_ind,
        in_consumption_pass_ind,
        in_consumption_layers,
        in_consumption_avg_eggs_per_layer,
        in_consumption_eggs_total,
        in_consumption_eggs_dozen_sold,
        in_consumption_price_per_dozen,
        in_consumption_expected_revenue,
        in_consumption_reported_revenue,
        in_consumption_revenue_variance,
        in_consumption_revenue_varinc_lmt,
        in_hatching_pass_ind,
        in_hatching_layers,
        in_hatching_avg_eggs_per_layer,
        in_hatching_eggs_total,
        in_hatching_eggs_dozen_sold,
        in_hatching_price_per_dozen,
        in_hatching_expected_revenue,
        in_hatching_reported_revenue,
        in_hatching_revenue_variance,
        in_hatching_revenue_variance_limt,
        in_reasonability_test_reslt_id,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );

end;
$$;
