create or replace procedure farms_reasonability_write_pkg.insert_farm_rsnblty_rev_pltry_brl_rslts(
    in in_reasonability_test_reslt_id farms.farm_rsn_rev_poultry_brl_rslts.reasonability_test_result_id%type,
    in in_has_poultry_broilers_ind farms.farm_rsn_rev_poultry_brl_rslts.has_poultry_broilers_ind%type,
    in in_poultry_broiler_pass_ind farms.farm_rsn_rev_poultry_brl_rslts.poultry_broiler_pass_ind%type,
    in in_has_chickens_ind farms.farm_rsn_rev_poultry_brl_rslts.has_chickens_ind%type,
    in in_chicken_pass_ind farms.farm_rsn_rev_poultry_brl_rslts.chicken_pass_ind%type,
    in in_chicken_avg_weight_kg farms.farm_rsn_rev_poultry_brl_rslts.chicken_avg_weight_kg%type,
    in in_chicken_expected_birds_sold farms.farm_rsn_rev_poultry_brl_rslts.chicken_expected_birds_sold%type,
    in in_chicken_price_per_bird farms.farm_rsn_rev_poultry_brl_rslts.chicken_price_per_bird%type,
    in in_chicken_expected_revenue farms.farm_rsn_rev_poultry_brl_rslts.chicken_expected_revenue%type,
    in in_chicken_reported_revenue farms.farm_rsn_rev_poultry_brl_rslts.chicken_reported_revenue%type,
    in in_chicken_produced_kg farms.farm_rsn_rev_poultry_brl_rslts.chicken_kg_produced%type,
    in in_chicken_revenue_variance farms.farm_rsn_rev_poultry_brl_rslts.chicken_revenue_variance%type,
    in in_chicken_revenue_variance_limit farms.farm_rsn_rev_poultry_brl_rslts.chicken_revenue_variance_limit%type,
    in in_has_turkeys_ind farms.farm_rsn_rev_poultry_brl_rslts.has_turkeys_ind%type,
    in in_turkey_pass_ind farms.farm_rsn_rev_poultry_brl_rslts.turkey_pass_ind%type,
    in in_turkey_avg_weight_kg farms.farm_rsn_rev_poultry_brl_rslts.turkey_avg_weight_kg%type,
    in in_turkey_expected_birds_sold farms.farm_rsn_rev_poultry_brl_rslts.turkey_expected_birds_sold%type,
    in in_turkey_price_per_bird farms.farm_rsn_rev_poultry_brl_rslts.turkey_price_per_bird%type,
    in in_turkey_expected_revenue farms.farm_rsn_rev_poultry_brl_rslts.turkey_expected_revenue%type,
    in in_turkey_reported_revenue farms.farm_rsn_rev_poultry_brl_rslts.turkey_reported_revenue%type,
    in in_turkey_produced_in_kg farms.farm_rsn_rev_poultry_brl_rslts.turkey_kg_produced%type,
    in in_turkey_revenue_variance farms.farm_rsn_rev_poultry_brl_rslts.turkey_revenue_variance%type,
    in in_turkey_revenue_variance_limit farms.farm_rsn_rev_poultry_brl_rslts.turkey_revenue_variance_limit%type,
    in in_user farms.farm_rsn_rev_poultry_brl_rslts.who_created%type
)
language plpgsql
as
$$
begin
    insert into farms.farm_rsn_rev_poultry_brl_rslts (
        rsn_rev_poultry_brl_rslt_id,
        reasonability_test_result_id,
        has_poultry_broilers_ind,
        poultry_broiler_pass_ind,
        has_chickens_ind,
        chicken_pass_ind,
        chicken_avg_weight_kg,
        chicken_expected_birds_sold,
        chicken_price_per_bird,
        chicken_expected_revenue,
        chicken_reported_revenue,
        chicken_kg_produced,
        chicken_revenue_variance,
        chicken_revenue_variance_limit,
        has_turkeys_ind,
        turkey_pass_ind,
        turkey_avg_weight_kg,
        turkey_expected_birds_sold,
        turkey_price_per_bird,
        turkey_expected_revenue,
        turkey_reported_revenue,
        turkey_revenue_variance,
        turkey_revenue_variance_limit,
        turkey_kg_produced,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        nextval('farms.farm_rrpbr_seq'),
        in_reasonability_test_reslt_id,
        in_has_poultry_broilers_ind,
        in_poultry_broiler_pass_ind,
        in_has_chickens_ind,
        in_chicken_pass_ind,
        in_chicken_avg_weight_kg,
        in_chicken_expected_birds_sold,
        in_chicken_price_per_bird,
        in_chicken_expected_revenue,
        in_chicken_reported_revenue,
        in_chicken_produced_kg,
        in_chicken_revenue_variance,
        in_chicken_revenue_variance_limit,
        in_has_turkeys_ind,
        in_turkey_pass_ind,
        in_turkey_avg_weight_kg,
        in_turkey_expected_birds_sold,
        in_turkey_price_per_bird,
        in_turkey_expected_revenue,
        in_turkey_reported_revenue,
        in_turkey_revenue_variance,
        in_turkey_revenue_variance_limit,
        in_turkey_produced_in_kg,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );

end;
$$;
