create or replace procedure farms_staging_pkg.insert_z03(
   in in_operation_number farms.z03_statement_information.operation_number%type,
   in in_participant_pin farms.z03_statement_information.participant_pin%type,
   in in_program_year farms.z03_statement_information.program_year%type,
   in in_partnership_pin farms.z03_statement_information.partnership_pin%type,
   in in_partnership_name farms.z03_statement_information.partnership_name%type,
   in in_partnership_percent farms.z03_statement_information.partnership_percent%type,
   in in_fiscal_year_start farms.z03_statement_information.fiscal_year_start%type,
   in in_fiscal_year_end farms.z03_statement_information.fiscal_year_end%type,
   in in_accounting_code farms.z03_statement_information.accounting_code%type,
   in in_landlord_ind farms.z03_statement_information.landlord_indicator%type,
   in in_crop_share_ind farms.z03_statement_information.crop_share_indicator%type,
   in in_feeder_member_ind farms.z03_statement_information.feeder_member_indicator%type,
   in in_gross_income farms.z03_statement_information.gross_income%type,
   in in_expenses farms.z03_statement_information.expenses%type,
   in in_net_income_before_adjustments farms.z03_statement_information.net_income_before_adjustments%type,
   in in_other_deductions farms.z03_statement_information.other_deductions%type,
   in in_inventory_adjustments farms.z03_statement_information.inventory_adjustments%type,
   in in_net_income_after_adjustments farms.z03_statement_information.net_income_after_adjustments%type,
   in in_business_use_of_home_expenses farms.z03_statement_information.business_use_of_home_expenses%type,
   in in_net_farm_income farms.z03_statement_information.net_farm_income%type,
   in in_crop_disaster_ind farms.z03_statement_information.crop_disaster_indicator%type,
   in in_livestock_disaster_ind farms.z03_statement_information.livestock_disaster_indicator%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.z03_statement_information (
        operation_number,
        participant_pin,
        program_year,
        partnership_pin,
        partnership_name,
        partnership_percent,
        fiscal_year_start,
        fiscal_year_end,
        accounting_code,
        landlord_indicator,
        crop_share_indicator,
        feeder_member_indicator,
        gross_income,
        expenses,
        net_income_before_adjustments,
        other_deductions,
        inventory_adjustments,
        net_income_after_adjustments,
        business_use_of_home_expenses,
        net_farm_income,
        crop_disaster_indicator,
        livestock_disaster_indicator,
        revision_count,
        create_user,
        create_date,
        update_user,
        update_date
    ) values (
        in_operation_number,
        in_participant_pin,
        in_program_year,
        in_partnership_pin,
        in_partnership_name,
        in_partnership_percent,
        in_fiscal_year_start,
        in_fiscal_year_end,
        in_accounting_code,
        in_landlord_ind,
        in_crop_share_ind,
        in_feeder_member_ind,
        in_gross_income,
        in_expenses,
        in_net_income_before_adjustments,
        in_other_deductions,
        in_inventory_adjustments,
        in_net_income_after_adjustments,
        in_business_use_of_home_expenses,
        in_net_farm_income,
        in_crop_disaster_ind,
        in_livestock_disaster_ind,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );
end;
$$;
