create or replace procedure farms_staging_pkg.insert_z02(
   in in_participant_pin farms.farm_z02_partpnt_farm_infos.participant_pin%type,
   in in_program_year farms.farm_z02_partpnt_farm_infos.program_year%type,
   in in_form_version_number farms.farm_z02_partpnt_farm_infos.form_version_number%type,
   in in_province_of_residence farms.farm_z02_partpnt_farm_infos.province_of_residence%type,
   in in_province_of_main_farmstead farms.farm_z02_partpnt_farm_infos.province_of_main_farmstead%type,
   in in_postmark_date farms.farm_z02_partpnt_farm_infos.postmark_date%type,
   in in_received_date farms.farm_z02_partpnt_farm_infos.received_date%type,
   in in_sole_proprietor_ind farms.farm_z02_partpnt_farm_infos.sole_proprietor_ind%type,
   in in_partnership_member_ind farms.farm_z02_partpnt_farm_infos.partnership_member_ind%type,
   in in_corporate_shareholder_ind farms.farm_z02_partpnt_farm_infos.corporate_shareholder_ind%type,
   in in_coop_member_ind farms.farm_z02_partpnt_farm_infos.coop_member_ind%type,
   in in_common_share_total farms.farm_z02_partpnt_farm_infos.common_share_total%type,
   in in_farm_years farms.farm_z02_partpnt_farm_infos.farm_years%type,
   in in_last_year_farming_ind farms.farm_z02_partpnt_farm_infos.last_year_farming_ind%type,
   in in_form_origin_code farms.farm_z02_partpnt_farm_infos.form_origin_code%type,
   in in_industry_code farms.farm_z02_partpnt_farm_infos.industry_code%type,
   in in_participant_profile_code farms.farm_z02_partpnt_farm_infos.participant_profile_code%type,
   in in_accrual_cash_conversion_ind farms.farm_z02_partpnt_farm_infos.accrual_cash_conversion_ind%type,
   in in_perishable_commodities_ind farms.farm_z02_partpnt_farm_infos.perishable_commodities_ind%type,
   in in_receipts_ind farms.farm_z02_partpnt_farm_infos.receipts_ind%type,
   in in_other_text_ind farms.farm_z02_partpnt_farm_infos.other_text_ind%type,
   in in_other_text farms.farm_z02_partpnt_farm_infos.other_text%type,
   in in_accrual_worksheet_ind farms.farm_z02_partpnt_farm_infos.accrual_worksheet_ind%type,
   in in_cwb_worksheet_ind farms.farm_z02_partpnt_farm_infos.cwb_worksheet_ind%type,
   in in_combined_this_year_ind farms.farm_z02_partpnt_farm_infos.combined_this_year_ind%type,
   in in_completed_production_cycle_ind farms.farm_z02_partpnt_farm_infos.completed_prod_cycle_ind%type,
   in in_disaster_ind farms.farm_z02_partpnt_farm_infos.disaster_ind%type,
   in in_copy_cob_to_contact_ind farms.farm_z02_partpnt_farm_infos.copy_cob_to_contact_ind%type,
   in in_municipality_code farms.farm_z02_partpnt_farm_infos.municipality_code%type,
   in in_form_version_effective_date farms.farm_z02_partpnt_farm_infos.form_version_effective_date%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.farm_z02_partpnt_farm_infos (
        participant_pin,
        program_year,
        form_version_number,
        province_of_residence,
        province_of_main_farmstead,
        postmark_date,
        received_date,
        sole_proprietor_ind,
        partnership_member_ind,
        corporate_shareholder_ind,
        coop_member_ind,
        common_share_total,
        farm_years,
        last_year_farming_ind,
        form_origin_code,
        industry_code,
        participant_profile_code,
        accrual_cash_conversion_ind,
        perishable_commodities_ind,
        receipts_ind,
        other_text_ind,
        other_text,
        accrual_worksheet_ind,
        cwb_worksheet_ind,
        combined_this_year_ind,
        completed_prod_cycle_ind,
        disaster_ind,
        copy_cob_to_contact_ind,
        municipality_code,
        form_version_effective_date,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        in_participant_pin,
        in_program_year,
        in_form_version_number,
        in_province_of_residence,
        in_province_of_main_farmstead,
        in_postmark_date,
        in_received_date,
        in_sole_proprietor_ind,
        in_partnership_member_ind,
        in_corporate_shareholder_ind,
        in_coop_member_ind,
        in_common_share_total,
        in_farm_years,
        in_last_year_farming_ind,
        in_form_origin_code,
        in_industry_code,
        in_participant_profile_code,
        in_accrual_cash_conversion_ind,
        in_perishable_commodities_ind,
        in_receipts_ind,
        in_other_text_ind,
        in_other_text,
        in_accrual_worksheet_ind,
        in_cwb_worksheet_ind,
        in_combined_this_year_ind,
        in_completed_production_cycle_ind,
        in_disaster_ind,
        in_copy_cob_to_contact_ind,
        in_municipality_code,
        in_form_version_effective_date,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );
end;
$$;
