create or replace procedure farms_staging_pkg.insert_z02(
   in in_participant_pin farms.z02_participant_farm_information.participant_pin%type,
   in in_program_year farms.z02_participant_farm_information.program_year%type,
   in in_form_version_number farms.z02_participant_farm_information.form_version_number%type,
   in in_province_of_residence farms.z02_participant_farm_information.province_of_residence%type,
   in in_province_of_main_farmstead farms.z02_participant_farm_information.province_of_main_farmstead%type,
   in in_postmark_date farms.z02_participant_farm_information.postmark_date%type,
   in in_received_date farms.z02_participant_farm_information.received_date%type,
   in in_sole_proprietor_ind farms.z02_participant_farm_information.sole_proprietor_indicator%type,
   in in_partnership_member_ind farms.z02_participant_farm_information.partnership_member_indicator%type,
   in in_corporate_shareholder_ind farms.z02_participant_farm_information.corporate_shareholder_indicator%type,
   in in_coop_member_ind farms.z02_participant_farm_information.coop_member_indicator%type,
   in in_common_share_total farms.z02_participant_farm_information.common_share_total%type,
   in in_farm_years farms.z02_participant_farm_information.farm_years%type,
   in in_last_year_farming_ind farms.z02_participant_farm_information.last_year_farming_indicator%type,
   in in_form_origin_code farms.z02_participant_farm_information.form_origin_code%type,
   in in_industry_code farms.z02_participant_farm_information.industry_code%type,
   in in_participant_profile_code farms.z02_participant_farm_information.participant_profile_code%type,
   in in_accrual_cash_conversion_ind farms.z02_participant_farm_information.accrual_cash_conversion_indicator%type,
   in in_perishable_commodities_ind farms.z02_participant_farm_information.perishable_commodities_indicator%type,
   in in_receipts_ind farms.z02_participant_farm_information.receipts_indicator%type,
   in in_other_text_ind farms.z02_participant_farm_information.other_text_indicator%type,
   in in_other_text farms.z02_participant_farm_information.other_text%type,
   in in_accrual_worksheet_ind farms.z02_participant_farm_information.accrual_worksheet_indicator%type,
   in in_cwb_worksheet_ind farms.z02_participant_farm_information.cwb_worksheet_indicator%type,
   in in_combined_this_year_ind farms.z02_participant_farm_information.combined_this_year_indicator%type,
   in in_completed_production_cycle_ind farms.z02_participant_farm_information.completed_production_cycle_indicator%type,
   in in_disaster_ind farms.z02_participant_farm_information.disaster_indicator%type,
   in in_copy_cob_to_contact_ind farms.z02_participant_farm_information.copy_cob_to_contact_indicator%type,
   in in_municipality_code farms.z02_participant_farm_information.municipality_code%type,
   in in_form_version_effective_date farms.z02_participant_farm_information.form_version_effective_date%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.z02_participant_farm_information (
        participant_pin,
        program_year,
        form_version_number,
        province_of_residence,
        province_of_main_farmstead,
        postmark_date,
        received_date,
        sole_proprietor_indicator,
        partnership_member_indicator,
        corporate_shareholder_indicator,
        coop_member_indicator,
        common_share_total,
        farm_years,
        last_year_farming_indicator,
        form_origin_code,
        industry_code,
        participant_profile_code,
        accrual_cash_conversion_indicator,
        perishable_commodities_indicator,
        receipts_indicator,
        other_text_indicator,
        other_text,
        accrual_worksheet_indicator,
        cwb_worksheet_indicator,
        combined_this_year_indicator,
        completed_production_cycle_indicator,
        disaster_indicator,
        copy_cob_to_contact_indicator,
        municipality_code,
        form_version_effective_date,
        revision_count,
        create_user,
        create_date,
        update_user,
        update_date
    ) values (
        in_participant_pin,
        in_program_year,
        in_form_version_number,
        in_province_of_residence,
        in_province_of_main_farmstead,
        in_postmark_date,
        in_received_date,
        in_sole_proprietor_ind,
        in_partnership_member_ind,
        in_corporate_shareholder_ind,
        in_coop_member_ind,
        in_common_share_total,
        in_farm_years,
        in_last_year_farming_ind,
        in_form_origin_code,
        in_industry_code,
        in_participant_profile_code,
        in_accrual_cash_conversion_ind,
        in_perishable_commodities_ind,
        in_receipts_ind,
        in_other_text_ind,
        in_other_text,
        in_accrual_worksheet_ind,
        in_cwb_worksheet_ind,
        in_combined_this_year_ind,
        in_completed_production_cycle_ind,
        in_disaster_ind,
        in_copy_cob_to_contact_ind,
        in_municipality_code,
        in_form_version_effective_date,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );
end;
$$;
