create or replace procedure farms_staging_pkg.insert_z03(
   in in_operation_number farms.farm_z03_statement_infos.operation_number%type,
   in in_participant_pin farms.farm_z03_statement_infos.participant_pin%type,
   in in_program_year farms.farm_z03_statement_infos.program_year%type,
   in in_partnership_pin farms.farm_z03_statement_infos.partnership_pin%type,
   in in_partnership_name farms.farm_z03_statement_infos.partnership_name%type,
   in in_partnership_percent farms.farm_z03_statement_infos.partnership_percent%type,
   in in_fiscal_year_start farms.farm_z03_statement_infos.fiscal_year_start%type,
   in in_fiscal_year_end farms.farm_z03_statement_infos.fiscal_year_end%type,
   in in_accounting_code farms.farm_z03_statement_infos.accounting_code%type,
   in in_landlord_ind farms.farm_z03_statement_infos.landlord_ind%type,
   in in_crop_share_ind farms.farm_z03_statement_infos.crop_share_ind%type,
   in in_feeder_member_ind farms.farm_z03_statement_infos.feeder_member_ind%type,
   in in_gross_income farms.farm_z03_statement_infos.gross_income%type,
   in in_expenses farms.farm_z03_statement_infos.expenses%type,
   in in_net_income_before_adjustments farms.farm_z03_statement_infos.net_income_before_adj%type,
   in in_other_deductions farms.farm_z03_statement_infos.other_deductions%type,
   in in_inventory_adjustments farms.farm_z03_statement_infos.inventory_adjustments%type,
   in in_net_income_after_adjustments farms.farm_z03_statement_infos.net_income_after_adj%type,
   in in_business_use_of_home_expenses farms.farm_z03_statement_infos.business_use_of_home_expenses%type,
   in in_net_farm_income farms.farm_z03_statement_infos.net_farm_income%type,
   in in_crop_disaster_ind farms.farm_z03_statement_infos.crop_disaster_ind%type,
   in in_livestock_disaster_ind farms.farm_z03_statement_infos.livestock_disaster_ind%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.farm_z03_statement_infos (
        operation_number,
        participant_pin,
        program_year,
        partnership_pin,
        partnership_name,
        partnership_percent,
        fiscal_year_start,
        fiscal_year_end,
        accounting_code,
        landlord_ind,
        crop_share_ind,
        feeder_member_ind,
        gross_income,
        expenses,
        net_income_before_adj,
        other_deductions,
        inventory_adjustments,
        net_income_after_adj,
        business_use_of_home_expenses,
        net_farm_income,
        crop_disaster_ind,
        livestock_disaster_ind,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        in_operation_number,
        in_participant_pin,
        in_program_year,
        in_partnership_pin,
        in_partnership_name,
        in_partnership_percent,
        in_fiscal_year_start,
        in_fiscal_year_end,
        in_accounting_code,
        in_landlord_ind,
        in_crop_share_ind,
        in_feeder_member_ind,
        in_gross_income,
        in_expenses,
        in_net_income_before_adjustments,
        in_other_deductions,
        in_inventory_adjustments,
        in_net_income_after_adjustments,
        in_business_use_of_home_expenses,
        in_net_farm_income,
        in_crop_disaster_ind,
        in_livestock_disaster_ind,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );
end;
$$;
