create or replace procedure farms_staging_pkg.insert_z01(
   in in_participant_pin farms.z01_participant_information.participant_pin%type,
   in in_sin_ctn_bn farms.z01_participant_information.sin_ctn_business_number%type,
   in in_sin farms.z01_participant_information.sin%type,
   in in_business_number farms.z01_participant_information.business_number%type,
   in in_trust_number farms.z01_participant_information.trust_number%type,
   in in_participant_type_code farms.z01_participant_information.participant_type_code%type,
   in in_participant_language farms.z01_participant_information.participant_language%type,
   in in_first_name farms.z01_participant_information.first_name%type,
   in in_last_name farms.z01_participant_information.last_name%type,
   in in_corp_name farms.z01_participant_information.corp_name%type,
   in in_address_1 farms.z01_participant_information.address_1%type,
   in in_address_2 farms.z01_participant_information.address_2%type,
   in in_city farms.z01_participant_information.city%type,
   in in_province farms.z01_participant_information.province%type,
   in in_postal_code farms.z01_participant_information.postal_code%type,
   in in_country farms.z01_participant_information.country%type,
   in in_participant_fax farms.z01_participant_information.participant_fax%type,
   in in_participant_phone_day farms.z01_participant_information.participant_phone_day%type,
   in in_participant_phone_evening farms.z01_participant_information.participant_phone_evening%type,
   in in_participant_cell_number farms.z01_participant_information.participant_cell_number%type,
   in in_participant_email_address farms.z01_participant_information.participant_email_address%type,
   in in_contact_first_name farms.z01_participant_information.contact_first_name%type,
   in in_contact_last_name farms.z01_participant_information.contact_last_name%type,
   in in_contact_business_name farms.z01_participant_information.contact_business_name%type,
   in in_contact_address_1 farms.z01_participant_information.contact_address_1%type,
   in in_contact_address_2 farms.z01_participant_information.contact_address_2%type,
   in in_contact_city farms.z01_participant_information.contact_city%type,
   in in_contact_province farms.z01_participant_information.contact_province%type,
   in in_contact_postal_code farms.z01_participant_information.contact_postal_code%type,
   in in_contact_phone_day farms.z01_participant_information.contact_phone_day%type,
   in in_contact_fax_number farms.z01_participant_information.contact_fax_number%type,
   in in_contact_cell_number farms.z01_participant_information.contact_cell_number%type,
   in in_public_office_ind farms.z01_participant_information.public_office_indicator%type,
   in in_ident_effective_date farms.z01_participant_information.identity_effective_date%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.z01_participant_information (
        participant_pin,
        sin,
        business_number,
        trust_number,
        participant_type_code,
        participant_language,
        first_name,
        last_name,
        corp_name,
        address_1,
        address_2,
        city,
        province,
        postal_code,
        country,
        participant_fax,
        participant_phone_day,
        participant_phone_evening,
        participant_cell_number,
        participant_email_address,
        contact_first_name,
        contact_last_name,
        contact_business_name,
        contact_address_1,
        contact_address_2,
        contact_city,
        contact_province,
        contact_postal_code,
        contact_phone_day,
        contact_fax_number,
        contact_cell_number,
        public_office_indicator,
        identity_effective_date,
        revision_count,
        create_user,
        create_date,
        update_user,
        update_date
    ) values (
       in_participant_pin,
       in_sin,
       in_business_number,
       in_trust_number,
       in_participant_type_code,
       in_participant_language,
       in_first_name,
       in_last_name,
       in_corp_name,
       in_address_1,
       in_address_2,
       in_city,
       in_province,
       in_postal_code,
       in_country,
       in_participant_fax,
       in_participant_phone_day,
       in_participant_phone_evening,
       in_participant_cell_number,
       in_participant_email_address,
       in_contact_first_name,
       in_contact_last_name,
       in_contact_business_name,
       in_contact_address_1,
       in_contact_address_2,
       in_contact_city,
       in_contact_province,
       in_contact_postal_code,
       in_contact_phone_day,
       in_contact_fax_number,
       in_contact_cell_number,
       in_public_office_ind,
       in_ident_effective_date,
       1,
       in_user,
       current_timestamp,
       in_user,
       current_timestamp
    );
end;
$$;
