//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.18 at 01:34:56 PST 
//


package ca.bc.gov.srm.farm.ui.domain.resultsstaging;


/**
 * Java content class for ERROR element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="ERROR">
 *   &lt;complexType>
 *     &lt;simpleContent>
 *       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *         &lt;attribute name="fileNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="rowNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;/extension>
 *     &lt;/simpleContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface ERROR
    extends javax.xml.bind.Element, ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERRORType
{


}
