//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.18 at 01:34:56 PST 
//


package ca.bc.gov.srm.farm.ui.domain.resultsstaging;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the ca.bc.gov.srm.farm.ui.domain.resultsstaging package. <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this class.
 * 
 */
public class ObjectFactory
    extends com.sun.xml.bind.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();

    static {
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOG.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.STAGINGLOGImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNINGType.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.WARNINGTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNING.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.WARNINGImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERROR.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.ERRORImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.ERRORSType.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.STAGINGLOGTypeImpl.ERRORSTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.STAGINGLOGTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.WARNINGSType.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.STAGINGLOGTypeImpl.WARNINGSTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERRORType.class), (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.ERRORTypeImpl.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.srm.farm.ui.domain.resultsstaging
     * 
     */
    public ObjectFactory() {
        super(new ca.bc.gov.srm.farm.ui.domain.resultsstaging.ObjectFactory.GrammarInfoImpl());
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @param value the value of the property to be set
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of STAGINGLOG
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOG createSTAGINGLOG()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOG) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOG.class)));
    }

    /**
     * Create an instance of WARNINGType
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNINGType createWARNINGType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNINGType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNINGType.class)));
    }

    /**
     * Create an instance of WARNING
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNING createWARNING()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNING) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.WARNING.class)));
    }

    /**
     * Create an instance of ERROR
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERROR createERROR()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERROR) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERROR.class)));
    }

    /**
     * Create an instance of STAGINGLOGTypeERRORSType
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.ERRORSType createSTAGINGLOGTypeERRORSType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.ERRORSType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.ERRORSType.class)));
    }

    /**
     * Create an instance of STAGINGLOGType
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType createSTAGINGLOGType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.class)));
    }

    /**
     * Create an instance of STAGINGLOGTypeWARNINGSType
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.WARNINGSType createSTAGINGLOGTypeWARNINGSType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.WARNINGSType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.STAGINGLOGType.WARNINGSType.class)));
    }

    /**
     * Create an instance of ERRORType
     * 
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERRORType createERRORType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERRORType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsstaging.ERRORType.class)));
    }

    private static class GrammarInfoImpl
        extends com.sun.xml.bind.GrammarInfo
    {


        public java.lang.Class getDefaultImplementation(java.lang.Class javaContentInterface) {
            return ((java.lang.Class) defaultImplementations.get(javaContentInterface));
        }

        public java.lang.Class getRootElement(java.lang.String uri, java.lang.String local) {
            if (("" == uri)&&("ERROR" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.ERRORImpl.class);
            }
            if (("" == uri)&&("WARNING" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.WARNINGImpl.class);
            }
            if (("" == uri)&&("STAGING_LOG" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsstaging.impl.STAGINGLOGImpl.class);
            }
            return null;
        }

        public java.lang.String[] getProbePoints() {
            return new java.lang.String[] {"", "ERROR", "", "WARNING", "", "STAGING_LOG"};
        }

    }

}
