create or replace procedure farms_staging_pkg.insert_z01(
   in in_participant_pin farms.farm_z01_participant_infos.participant_pin%type,
   in in_sin_ctn_bn farms.farm_z01_participant_infos.sin_ctn_bn%type,
   in in_sin farms.farm_z01_participant_infos.sin%type,
   in in_business_number farms.farm_z01_participant_infos.business_number%type,
   in in_trust_number farms.farm_z01_participant_infos.trust_number%type,
   in in_participant_type_code farms.farm_z01_participant_infos.participant_type_code%type,
   in in_participant_language farms.farm_z01_participant_infos.participant_language%type,
   in in_first_name farms.farm_z01_participant_infos.first_name%type,
   in in_last_name farms.farm_z01_participant_infos.last_name%type,
   in in_corp_name farms.farm_z01_participant_infos.corp_name%type,
   in in_address_1 farms.farm_z01_participant_infos.address_1%type,
   in in_address_2 farms.farm_z01_participant_infos.address_2%type,
   in in_city farms.farm_z01_participant_infos.city%type,
   in in_province farms.farm_z01_participant_infos.province%type,
   in in_postal_code farms.farm_z01_participant_infos.postal_code%type,
   in in_country farms.farm_z01_participant_infos.country%type,
   in in_participant_fax farms.farm_z01_participant_infos.participant_fax%type,
   in in_participant_phone_day farms.farm_z01_participant_infos.participant_phone_day%type,
   in in_participant_phone_evening farms.farm_z01_participant_infos.participant_phone_evening%type,
   in in_participant_cell_number farms.farm_z01_participant_infos.participant_cell_number%type,
   in in_participant_email_address farms.farm_z01_participant_infos.participant_email_address%type,
   in in_contact_first_name farms.farm_z01_participant_infos.contact_first_name%type,
   in in_contact_last_name farms.farm_z01_participant_infos.contact_last_name%type,
   in in_contact_business_name farms.farm_z01_participant_infos.contact_business_name%type,
   in in_contact_address_1 farms.farm_z01_participant_infos.contact_address_1%type,
   in in_contact_address_2 farms.farm_z01_participant_infos.contact_address_2%type,
   in in_contact_city farms.farm_z01_participant_infos.contact_city%type,
   in in_contact_province farms.farm_z01_participant_infos.contact_province%type,
   in in_contact_postal_code farms.farm_z01_participant_infos.contact_postal_code%type,
   in in_contact_phone_day farms.farm_z01_participant_infos.contact_phone_day%type,
   in in_contact_fax_number farms.farm_z01_participant_infos.contact_fax_number%type,
   in in_contact_cell_number farms.farm_z01_participant_infos.contact_cell_number%type,
   in in_public_office_ind farms.farm_z01_participant_infos.public_office_ind%type,
   in in_ident_effective_date farms.farm_z01_participant_infos.ident_effective_date%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.farm_z01_participant_infos (
        participant_pin,
        sin,
        business_number,
        trust_number,
        sin_ctn_bn,
        participant_type_code,
        participant_language,
        first_name,
        last_name,
        corp_name,
        address_1,
        address_2,
        city,
        province,
        postal_code,
        country,
        participant_fax,
        participant_phone_day,
        participant_phone_evening,
        participant_cell_number,
        participant_email_address,
        contact_first_name,
        contact_last_name,
        contact_business_name,
        contact_address_1,
        contact_address_2,
        contact_city,
        contact_province,
        contact_postal_code,
        contact_phone_day,
        contact_fax_number,
        contact_cell_number,
        public_office_ind,
        ident_effective_date,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
       in_participant_pin,
       in_sin,
       in_business_number,
       in_trust_number,
       in_sin_ctn_bn,
       in_participant_type_code,
       in_participant_language,
       in_first_name,
       in_last_name,
       in_corp_name,
       in_address_1,
       in_address_2,
       in_city,
       in_province,
       in_postal_code,
       in_country,
       in_participant_fax,
       in_participant_phone_day,
       in_participant_phone_evening,
       in_participant_cell_number,
       in_participant_email_address,
       in_contact_first_name,
       in_contact_last_name,
       in_contact_business_name,
       in_contact_address_1,
       in_contact_address_2,
       in_contact_city,
       in_contact_province,
       in_contact_postal_code,
       in_contact_phone_day,
       in_contact_fax_number,
       in_contact_cell_number,
       in_public_office_ind,
       in_ident_effective_date,
       1,
       in_user,
       current_timestamp,
       in_user,
       current_timestamp
    );
end;
$$;
