$kind: http-request
name: Get Configuration Parameters
url: "{{baseUrl}}/configurationParameters"
method: GET
auth:
  type: bearer
  credentials:
    token: "{{access_token}}"
scripts:
  - type: afterResponse
    code: "pm.test(\"Status code is 200\", function () {\r

      \    pm.response.to.have.status(200);\r

      });\r

      \r

      const json = pm.response.json();\r

      \r

      pm.test(\"Response contains @type = ConfigurationParameterListModel\",
      function() {\r

      \    pm.expect(json).to.have.property(\"@type\");\r

      \    pm.expect(json['@type']).to.be.equal(\"ConfigurationParameterListMod\
      el\");\r

      });\r

      \r

      pm.test(\"configurationParameterList is not empty\", function() {\r

      \    pm.expect(json).to.have.property(\"configurationParameterList\");\r

      \    pm.expect(json.configurationParameterList.length).to.be.greaterThan(\
      0);\r

      });\r

      \r

      pm.test(\"configurationParameterList[0] contains @type =
      ConfigurationParameterModel\", function() {\r

      \    pm.expect(json.configurationParameterList[0]).to.have.property(\"@ty\
      pe\");\r

      \    pm.expect(json.configurationParameterList[0]['@type']).to.be.equal(\
      \"ConfigurationParameterModel\");\r

      });"
    language: text/javascript
order: 4490599427255475
