package ca.bc.gov.srm.farm.ui.struts.report;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ca.bc.gov.srm.farm.service.ReportService;
import ca.bc.gov.srm.farm.service.ServiceFactory;
import ca.bc.gov.srm.farm.ui.struts.SecureAction;
import ca.bc.gov.srm.farm.util.IOUtils;


/**
 * Allows the user to retrieve the resulting output file generated by
 * BackgroundReportGenerateAction.
 * 
 * Return it as a stream to the browser.
 */
public class BackgroundReportDownloadAction extends SecureAction {
	private Logger log = LoggerFactory.getLogger(getClass());

  /**
   * doExecute.
   *
   * @param   mapping     mapping
   * @param   actionForm  actionForm
   * @param   request     request
   * @param   response    response
   *
   * @return  The return value
   *
   * @throws  Exception  On Exception
   */
  @Override
  public ActionForward doExecute(
  	final ActionMapping mapping,
    final ActionForm actionForm, 
    final HttpServletRequest request,
    final HttpServletResponse response) throws Exception {
    log.debug("<doExecute");

    ReportForm form = (ReportForm) actionForm;
    ReportService service = ServiceFactory.getReportService();
    String reportType = form.getReportType();
    String contentType = IOUtils.CONTENT_TYPE_CSV;
    String reportFileName = service.getBackgroundReportFileName(reportType);

    File tempDir = IOUtils.getTempDir(); 
    
    File outputFile = new File(tempDir, reportFileName);
    IOUtils.writeFileToResponse(response, outputFile, contentType);

    log.debug(">doExecute");
    return null;
  }
  
}
