drop procedure if exists farms_bpu_pkg.insert_staging_row(
    bigint,
    smallint,
    varchar,
    varchar,
    varchar,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    numeric,
    varchar
);

create or replace procedure farms_bpu_pkg.insert_staging_row(
   in in_line_number farms.farm_zbpu_benchmark_per_units.line_number%type,
   in in_program_year farms.farm_zbpu_benchmark_per_units.program_year%type,
   in in_municipality_code farms.farm_zbpu_benchmark_per_units.municipality_code%type,
   in in_inventory_item_code farms.farm_zbpu_benchmark_per_units.inventory_item_code%type,
   in in_unit_comment farms.farm_zbpu_benchmark_per_units.unit_comment%type,
   in in_year_minus_6_margin farms.farm_zbpu_benchmark_per_units.year_minus_6_margin%type,
   in in_year_minus_5_margin farms.farm_zbpu_benchmark_per_units.year_minus_5_margin%type,
   in in_year_minus_4_margin farms.farm_zbpu_benchmark_per_units.year_minus_4_margin%type,
   in in_year_minus_3_margin farms.farm_zbpu_benchmark_per_units.year_minus_3_margin%type,
   in in_year_minus_2_margin farms.farm_zbpu_benchmark_per_units.year_minus_2_margin%type,
   in in_year_minus_1_margin farms.farm_zbpu_benchmark_per_units.year_minus_1_margin%type,
   in in_year_minus_6_expense farms.farm_zbpu_benchmark_per_units.year_minus_6_expense%type,
   in in_year_minus_5_expense farms.farm_zbpu_benchmark_per_units.year_minus_5_expense%type,
   in in_year_minus_4_expense farms.farm_zbpu_benchmark_per_units.year_minus_4_expense%type,
   in in_year_minus_3_expense farms.farm_zbpu_benchmark_per_units.year_minus_3_expense%type,
   in in_year_minus_2_expense farms.farm_zbpu_benchmark_per_units.year_minus_2_expense%type,
   in in_year_minus_1_expense farms.farm_zbpu_benchmark_per_units.year_minus_1_expense%type,
   in in_file_location farms.farm_zbpu_benchmark_per_units.file_location%type,
   in in_user varchar
)
language plpgsql
as $$
begin
    insert into farms.farm_zbpu_benchmark_per_units (
        line_number,
        program_year,
        municipality_code,
        inventory_item_code,
        unit_comment,
        year_minus_6_margin,
        year_minus_5_margin,
        year_minus_4_margin,
        year_minus_3_margin,
        year_minus_2_margin,
        year_minus_1_margin,
        year_minus_6_expense,
        year_minus_5_expense,
        year_minus_4_expense,
        year_minus_3_expense,
        year_minus_2_expense,
        year_minus_1_expense,
        file_location,
        revision_count,
        who_created,
        when_created,
        who_updated,
        when_updated
    ) values (
        in_line_number,
        in_program_year,
        in_municipality_code,
        in_inventory_item_code,
        in_unit_comment,
        in_year_minus_6_margin,
        in_year_minus_5_margin,
        in_year_minus_4_margin,
        in_year_minus_3_margin,
        in_year_minus_2_margin,
        in_year_minus_1_margin,
        in_year_minus_6_expense,
        in_year_minus_5_expense,
        in_year_minus_4_expense,
        in_year_minus_3_expense,
        in_year_minus_2_expense,
        in_year_minus_1_expense,
        in_file_location,
        1,
        in_user,
        current_timestamp,
        in_user,
        current_timestamp
    );
end;
$$;
