create or replace function farms_read_pkg.read_sc_clm(
    in sc_ids bigint[]
)
returns table(
    agristability_claim_id              farms.farm_agristability_claims.agristability_claim_id%type,
    administrative_cost_share           farms.farm_agristability_claims.administrative_cost_share%type,
    late_application_penalty            farms.farm_agristability_claims.late_application_penalty%type,
    maximum_contribution                farms.farm_agristability_claims.maximum_contribution%type,
    outstanding_fees                    farms.farm_agristability_claims.outstanding_fees%type,
    program_year_margin                 farms.farm_agristability_claims.program_year_margin%type,
    prod_insur_deemed_benefit           farms.farm_agristability_claims.prod_insur_deemed_benefit%type,
    program_year_payments_received      farms.farm_agristability_claims.program_year_payments_received%type,
    allocated_reference_margin          farms.farm_agristability_claims.allocated_reference_margin%type,
    repayment_of_cash_advances          farms.farm_agristability_claims.repayment_of_cash_advances%type,
    total_payment                       farms.farm_agristability_claims.total_payment%type,
    supply_managed_commodities_adj      farms.farm_agristability_claims.supply_managed_commodities_adj%type,
    producer_share                      farms.farm_agristability_claims.producer_share%type,
    federal_contributions               farms.farm_agristability_claims.federal_contributions%type,
    provincial_contributions            farms.farm_agristability_claims.provincial_contributions%type,
    interim_contributions               farms.farm_agristability_claims.interim_contributions%type,
    whole_farm_allocation               farms.farm_agristability_claims.whole_farm_allocation%type,
    tier2_margin_decline                farms.farm_agristability_claims.tier2_margin_decline%type,
    tier3_margin_decline                farms.farm_agristability_claims.tier3_margin_decline%type,
    tier2_benefit                       farms.farm_agristability_claims.tier2_benefit%type,
    tier3_benefit                       farms.farm_agristability_claims.tier3_benefit%type,
    margin_decline                      farms.farm_agristability_claims.margin_decline%type,
    negative_margin_decline             farms.farm_agristability_claims.negative_margin_decline%type,
    negative_margin_benefit             farms.farm_agristability_claims.negative_margin_benefit%type,
    total_benefit                       farms.farm_agristability_claims.total_benefit%type,
    adjusted_reference_margin           farms.farm_agristability_claims.adjusted_reference_margin%type,
    unadjusted_reference_margin         farms.farm_agristability_claims.unadjusted_reference_margin%type,
    reference_margin_limit              farms.farm_agristability_claims.reference_margin_limit%type,
    reference_margin_limit_cap          farms.farm_agristability_claims.reference_margin_limit_cap%type,
    ref_marg_limit_for_bnft_calc        farms.farm_agristability_claims.ref_marg_limit_for_bnft_calc%type,
    structural_change_code              farms.farm_agristability_claims.structural_change_code%type,
    structural_change_desc              farms.farm_structural_change_codes.description%type,
    expense_structural_change_code      farms.farm_agristability_claims.expense_structural_change_code%type,
    expense_structural_change_desc      farms.farm_structural_change_codes.description%type,
    agristability_scenario_id           farms.farm_agristability_claims.agristability_scenario_id%type,
    tier2_trigger                       farms.farm_agristability_claims.tier2_trigger%type,
    tier3_trigger                       farms.farm_agristability_claims.tier3_trigger%type,
    benefit_before_deductions           farms.farm_agristability_claims.benefit_before_deductions%type,
    benefit_after_prod_insur_ded        farms.farm_agristability_claims.benefit_after_prod_insur_ded%type,
    applied_benefit_percent             farms.farm_agristability_claims.applied_benefit_percent%type,
    benefit_after_appl_benefit_pct      farms.farm_agristability_claims.benefit_after_appl_benefit_pct%type,
    interim_benefit_percent             farms.farm_agristability_claims.interim_benefit_percent%type,
    benefit_after_interim_ded           farms.farm_agristability_claims.benefit_after_interim_ded%type,
    payment_cap                         farms.farm_agristability_claims.payment_cap%type,
    benefit_after_payment_cap           farms.farm_agristability_claims.benefit_after_payment_cap%type,
    late_enrolment_penalty              farms.farm_agristability_claims.late_enrolment_penalty%type,
    bnft_after_late_enrol_penalty       farms.farm_agristability_claims.bnft_after_late_enrol_penalty%type,
    late_enr_pnlty_aft_apl_ben_pct      farms.farm_agristability_claims.late_enr_pnlty_aft_apl_ben_pct%type,
    standard_benefit                    farms.farm_agristability_claims.standard_benefit%type,
    enh_margin_decline                  farms.farm_agristability_claims.enh_margin_decline%type,
    enh_ref_margin_for_beneft_calc      farms.farm_agristability_claims.enh_ref_margin_for_beneft_calc%type,
    enh_positive_margin_decline         farms.farm_agristability_claims.enh_positive_margin_decline%type,
    enh_positive_margin_benefit         farms.farm_agristability_claims.enh_positive_margin_benefit%type,
    enh_negative_margin_decline         farms.farm_agristability_claims.enh_negative_margin_decline%type,
    enh_negative_margin_benefit         farms.farm_agristability_claims.enh_negative_margin_benefit%type,
    enh_benefit_before_deductions       farms.farm_agristability_claims.enh_benefit_before_deductions%type,
    enh_benefit_after_prodins_ded       farms.farm_agristability_claims.enh_benefit_after_prodins_ded%type,
    enh_benefit_after_interim_ded       farms.farm_agristability_claims.enh_benefit_after_interim_ded%type,
    enh_benefit_after_payment_cap       farms.farm_agristability_claims.enh_benefit_after_payment_cap%type,
    enh_total_benefit                   farms.farm_agristability_claims.enh_total_benefit%type,
    enh_additional_benefit              farms.farm_agristability_claims.enh_additional_benefit%type,
    enh_late_enrolment_penalty          farms.farm_agristability_claims.enh_late_enrolment_penalty%type,
    enh_bnft_aftr_late_enr_penalty      farms.farm_agristability_claims.enh_bnft_aftr_late_enr_penalty%type,
    enh_bnft_aftr_applied_bnft_pct      farms.farm_agristability_claims.enh_bnft_aftr_applied_bnft_pct%type,
    enh_lat_en_pnlty_af_apl_bn_pct      farms.farm_agristability_claims.enh_lat_en_pnlty_af_apl_bn_pct%type,
    ratio_adj_reference_margin          farms.farm_agristability_claims.ratio_adj_reference_margin%type,
    additive_adj_reference_margin       farms.farm_agristability_claims.additive_adj_reference_margin%type,
    revision_count                      farms.farm_agristability_claims.revision_count%type,
    pi_deemed_bnft_manual_calc_ind      farms.farm_agristability_claims.pi_deemed_bnft_manual_calc_ind%type
)
language sql
as $$
    select agristability_claim_id,
           administrative_cost_share,
           late_application_penalty,
           maximum_contribution,
           outstanding_fees,
           program_year_margin,
           prod_insur_deemed_benefit,
           program_year_payments_received,
           allocated_reference_margin,
           repayment_of_cash_advances,
           total_payment,
           supply_managed_commodities_adj,
           producer_share,
           federal_contributions,
           provincial_contributions,
           interim_contributions,
           whole_farm_allocation,
           tier2_margin_decline,
           tier3_margin_decline,
           tier2_benefit,
           tier3_benefit,
           margin_decline,
           negative_margin_decline,
           negative_margin_benefit,
           total_benefit,
           adjusted_reference_margin,
           unadjusted_reference_margin,
           reference_margin_limit,
           reference_margin_limit_cap,
           ref_marg_limit_for_bnft_calc,
           clm.structural_change_code,
           scc.description structural_change_desc,
           clm.expense_structural_change_code,
           escc.description expense_structural_change_desc,
           agristability_scenario_id,
           tier2_trigger,
           tier3_trigger,
           benefit_before_deductions,
           benefit_after_prod_insur_ded,
           applied_benefit_percent,
           benefit_after_appl_benefit_pct,
           interim_benefit_percent,
           benefit_after_interim_ded,
           payment_cap,
           benefit_after_payment_cap,
           late_enrolment_penalty,
           bnft_after_late_enrol_penalty,
           late_enr_pnlty_aft_apl_ben_pct,
           standard_benefit,
           enh_margin_decline,
           enh_ref_margin_for_beneft_calc,
           enh_positive_margin_decline,
           enh_positive_margin_benefit,
           enh_negative_margin_decline,
           enh_negative_margin_benefit,
           enh_benefit_before_deductions,
           enh_benefit_after_prodins_ded,
           enh_benefit_after_interim_ded,
           enh_benefit_after_payment_cap,
           enh_total_benefit,
           enh_additional_benefit,
           enh_late_enrolment_penalty,
           enh_bnft_aftr_late_enr_penalty,
           enh_bnft_aftr_applied_bnft_pct,
           enh_lat_en_pnlty_af_apl_bn_pct,
           ratio_adj_reference_margin,
           additive_adj_reference_margin,
           clm.revision_count,
           clm.pi_deemed_bnft_manual_calc_ind
    from farms.farm_agristability_claims clm
    left join farms.farm_structural_change_codes scc on scc.structural_change_code = clm.structural_change_code
    left join farms.farm_structural_change_codes escc on escc.structural_change_code = clm.expense_structural_change_code
    where clm.agristability_scenario_id = any(sc_ids);
$$;
