create or replace function farms_read_pkg.read_enw_enrolment(
    in in_agristability_scenario_id farms.farm_agristability_scenarios.agristability_scenario_id%type
)
returns table(
    scenario_enrolment_id           farms.farm_scenario_enrolments.scenario_enrolment_id%type,
    enrolment_year                  farms.farm_scenario_enrolments.enrolment_year%type,
    enrolment_fee                   farms.farm_scenario_enrolments.enrolment_fee%type,
    contribution_margin             farms.farm_scenario_enrolments.contribution_margin%type,
    benefit_calculated_ind          farms.farm_scenario_enrolments.benefit_calculated_ind%type,
    proxy_margins_calculated_ind    farms.farm_scenario_enrolments.proxy_margins_calculated_ind%type,
    manual_calculated_ind           farms.farm_scenario_enrolments.manual_calculated_ind%type,
    has_productive_units_ind        farms.farm_scenario_enrolments.has_productive_units_ind%type,
    has_benchmark_per_units_ind     farms.farm_scenario_enrolments.has_benchmark_per_units_ind%type,
    benefit_enrolment_fee           farms.farm_scenario_enrolments.benefit_enrolment_fee%type,
    benefit_contribution_margin     farms.farm_scenario_enrolments.benefit_contribution_margin%type,
    proxy_enrolment_fee             farms.farm_scenario_enrolments.proxy_enrolment_fee%type,
    proxy_contribution_margin       farms.farm_scenario_enrolments.proxy_contribution_margin%type,
    manual_enrolment_fee            farms.farm_scenario_enrolments.manual_enrolment_fee%type,
    manual_contribution_margin      farms.farm_scenario_enrolments.manual_contribution_margin%type,
    margin_year_minus_2             farms.farm_scenario_enrolments.margin_year_minus_2%type,
    margin_year_minus_3             farms.farm_scenario_enrolments.margin_year_minus_3%type,
    margin_year_minus_4             farms.farm_scenario_enrolments.margin_year_minus_4%type,
    margin_year_minus_5             farms.farm_scenario_enrolments.margin_year_minus_5%type,
    margin_year_minus_6             farms.farm_scenario_enrolments.margin_year_minus_6%type,
    margin_year_minus_2_ind         farms.farm_scenario_enrolments.margin_year_minus_2_ind%type,
    margin_year_minus_3_ind         farms.farm_scenario_enrolments.margin_year_minus_3_ind%type,
    margin_year_minus_4_ind         farms.farm_scenario_enrolments.margin_year_minus_4_ind%type,
    margin_year_minus_5_ind         farms.farm_scenario_enrolments.margin_year_minus_5_ind%type,
    margin_year_minus_6_ind         farms.farm_scenario_enrolments.margin_year_minus_6_ind%type,
    benefit_margin_year_minus_2     farms.farm_scenario_enrolments.benefit_margin_year_minus_2%type,
    benefit_margin_year_minus_3     farms.farm_scenario_enrolments.benefit_margin_year_minus_3%type,
    benefit_margin_year_minus_4     farms.farm_scenario_enrolments.benefit_margin_year_minus_4%type,
    benefit_margin_year_minus_5     farms.farm_scenario_enrolments.benefit_margin_year_minus_5%type,
    benefit_margin_year_minus_6     farms.farm_scenario_enrolments.benefit_margin_year_minus_6%type,
    benefit_margn_year_minus_2_ind  farms.farm_scenario_enrolments.benefit_margn_year_minus_2_ind%type,
    benefit_margn_year_minus_3_ind  farms.farm_scenario_enrolments.benefit_margn_year_minus_3_ind%type,
    benefit_margn_year_minus_4_ind  farms.farm_scenario_enrolments.benefit_margn_year_minus_4_ind%type,
    benefit_margn_year_minus_5_ind  farms.farm_scenario_enrolments.benefit_margn_year_minus_5_ind%type,
    benefit_margn_year_minus_6_ind  farms.farm_scenario_enrolments.benefit_margn_year_minus_6_ind%type,
    proxy_margin_year_minus_2       farms.farm_scenario_enrolments.proxy_margin_year_minus_2%type,
    proxy_margin_year_minus_3       farms.farm_scenario_enrolments.proxy_margin_year_minus_3%type,
    proxy_margin_year_minus_4       farms.farm_scenario_enrolments.proxy_margin_year_minus_4%type,
    manual_margin_year_minus_2      farms.farm_scenario_enrolments.manual_margin_year_minus_2%type,
    manual_margin_year_minus_3      farms.farm_scenario_enrolments.manual_margin_year_minus_3%type,
    manual_margin_year_minus_4      farms.farm_scenario_enrolments.manual_margin_year_minus_4%type,
    combined_farm_percent           farms.farm_scenario_enrolments.combined_farm_percent%type,
    enrolment_calc_type_code        farms.farm_scenario_enrolments.enrolment_calc_type_code%type,
    revision_count                  farms.farm_scenario_enrolments.revision_count%type
)
language sql
as $$
    select se.scenario_enrolment_id,
           se.enrolment_year,
           se.enrolment_fee,
           se.contribution_margin,
           se.benefit_calculated_ind,
           se.proxy_margins_calculated_ind,
           se.manual_calculated_ind,
           se.has_productive_units_ind,
           se.has_benchmark_per_units_ind,
           se.benefit_enrolment_fee,
           se.benefit_contribution_margin,
           se.proxy_enrolment_fee,
           se.proxy_contribution_margin,
           se.manual_enrolment_fee,
           se.manual_contribution_margin,
           se.margin_year_minus_2,
           se.margin_year_minus_3,
           se.margin_year_minus_4,
           se.margin_year_minus_5,
           se.margin_year_minus_6,
           se.margin_year_minus_2_ind,
           se.margin_year_minus_3_ind,
           se.margin_year_minus_4_ind,
           se.margin_year_minus_5_ind,
           se.margin_year_minus_6_ind,
           se.benefit_margin_year_minus_2,
           se.benefit_margin_year_minus_3,
           se.benefit_margin_year_minus_4,
           se.benefit_margin_year_minus_5,
           se.benefit_margin_year_minus_6,
           se.benefit_margn_year_minus_2_ind,
           se.benefit_margn_year_minus_3_ind,
           se.benefit_margn_year_minus_4_ind,
           se.benefit_margn_year_minus_5_ind,
           se.benefit_margn_year_minus_6_ind,
           se.proxy_margin_year_minus_2,
           se.proxy_margin_year_minus_3,
           se.proxy_margin_year_minus_4,
           se.manual_margin_year_minus_2,
           se.manual_margin_year_minus_3,
           se.manual_margin_year_minus_4,
           se.combined_farm_percent,
           se.enrolment_calc_type_code,
           se.revision_count
    from farms.farm_scenario_enrolments se
    where se.agristability_scenario_id = in_agristability_scenario_id;
$$;
