create or replace function farms_read_pkg.read_sc_tot_mgn(
    in sc_ids bigint[]
)
returns table(
    benefit_calc_total_id               farms.farm_benefit_calc_totals.benefit_calc_total_id%type,
    accrual_adjs_crop_inventory         farms.farm_benefit_calc_totals.accrual_adjs_crop_inventory%type,
    accrual_adjs_lvstck_inventory       farms.farm_benefit_calc_totals.accrual_adjs_lvstck_inventory%type,
    accrual_adjs_payables               farms.farm_benefit_calc_totals.accrual_adjs_payables%type,
    accrual_adjs_purchased_inputs       farms.farm_benefit_calc_totals.accrual_adjs_purchased_inputs%type,
    accrual_adjs_receivables            farms.farm_benefit_calc_totals.accrual_adjs_receivables%type,
    structural_change_adjs              farms.farm_benefit_calc_totals.structural_change_adjs%type,
    total_allowable_expenses            farms.farm_benefit_calc_totals.total_allowable_expenses%type,
    total_allowable_income              farms.farm_benefit_calc_totals.total_allowable_income%type,
    unadjusted_production_margin        farms.farm_benefit_calc_totals.unadjusted_production_margin%type,
    production_marg_accr_adjs           farms.farm_benefit_calc_totals.production_marg_accr_adjs%type,
    production_marg_aft_str_changs      farms.farm_benefit_calc_totals.production_marg_aft_str_changs%type,
    agristability_scenario_id           farms.farm_benefit_calc_totals.agristability_scenario_id%type,
    fiscal_year_pro_rate_adjs           farms.farm_benefit_calc_totals.fiscal_year_pro_rate_adjs%type,
    farm_size_ratio                     farms.farm_benefit_calc_totals.farm_size_ratio%type,
    expense_farm_size_ratio             farms.farm_benefit_calc_totals.expense_farm_size_ratio%type,
    structural_change_notable_ind       farms.farm_benefit_calc_totals.structural_change_notable_ind%type,
    bpu_lead_ind                        farms.farm_benefit_calc_totals.bpu_lead_ind%type,
    supply_mngd_commodity_income        farms.farm_benefit_calc_totals.supply_mngd_commodity_income%type,
    unadjusted_allowable_income         farms.farm_benefit_calc_totals.unadjusted_allowable_income%type,
    yardage_income                      farms.farm_benefit_calc_totals.yardage_income%type,
    program_payment_income              farms.farm_benefit_calc_totals.program_payment_income%type,
    total_unallowable_income            farms.farm_benefit_calc_totals.total_unallowable_income%type,
    unadjusted_allowable_expenses       farms.farm_benefit_calc_totals.unadjusted_allowable_expenses%type,
    yardage_expenses                    farms.farm_benefit_calc_totals.yardage_expenses%type,
    contract_work_expenses              farms.farm_benefit_calc_totals.contract_work_expenses%type,
    manual_expenses                     farms.farm_benefit_calc_totals.manual_expenses%type,
    total_unallowable_expenses          farms.farm_benefit_calc_totals.total_unallowable_expenses%type,
    deferred_program_payments           farms.farm_benefit_calc_totals.deferred_program_payments%type,
    expense_accr_adjs                   farms.farm_benefit_calc_totals.expense_accr_adjs%type,
    expense_structural_chg_adjs         farms.farm_benefit_calc_totals.expense_structural_chg_adjs%type,
    expenses_aft_str_chg                farms.farm_benefit_calc_totals.expenses_aft_str_chg%type,
    ratio_structural_change_adjs        farms.farm_benefit_calc_totals.ratio_structural_change_adjs%type,
    additive_structural_change_adj      farms.farm_benefit_calc_totals.additive_structural_change_adj%type,
    ratio_prod_marg_aft_str_changs      farms.farm_benefit_calc_totals.ratio_prod_marg_aft_str_changs%type,
    additive_prod_marg_aft_str_chg      farms.farm_benefit_calc_totals.additive_prod_marg_aft_str_chg%type,
    ratio_struc_chg_notable_ind         farms.farm_benefit_calc_totals.ratio_struc_chg_notable_ind%type,
    additive_struc_chg_notable_ind      farms.farm_benefit_calc_totals.additive_struc_chg_notable_ind%type,
    revision_count                      farms.farm_benefit_calc_totals.revision_count%type
)
language sql
as $$
    select benefit_calc_total_id,
           accrual_adjs_crop_inventory,
           accrual_adjs_lvstck_inventory,
           accrual_adjs_payables,
           accrual_adjs_purchased_inputs,
           accrual_adjs_receivables,
           structural_change_adjs,
           total_allowable_expenses,
           total_allowable_income,
           unadjusted_production_margin,
           production_marg_accr_adjs,
           production_marg_aft_str_changs,
           agristability_scenario_id,
           fiscal_year_pro_rate_adjs,
           farm_size_ratio,
           expense_farm_size_ratio,
           structural_change_notable_ind,
           bpu_lead_ind,
           supply_mngd_commodity_income,
           unadjusted_allowable_income,
           yardage_income,
           program_payment_income,
           total_unallowable_income,
           unadjusted_allowable_expenses,
           yardage_expenses,
           contract_work_expenses,
           manual_expenses,
           total_unallowable_expenses,
           deferred_program_payments,
           expense_accr_adjs,
           expense_structural_chg_adjs,
           expenses_aft_str_chg,
           ratio_structural_change_adjs,
           additive_structural_change_adj,
           ratio_prod_marg_aft_str_changs,
           additive_prod_marg_aft_str_chg,
           ratio_struc_chg_notable_ind,
           additive_struc_chg_notable_ind,
           revision_count
    from farms.farm_benefit_calc_totals ttl
    where ttl.agristability_scenario_id = any(sc_ids);
$$;
