export CATALINA_OPTS="\
  -DPOSTGRES_RESOURCE_NAME=$POSTGRES_RESOURCE_NAME \
  -DPOSTGRES_URL=$POSTGRES_URL \
  -DPOSTGRES_USERNAME=$POSTGRES_USERNAME \
  -DPOSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  -DPOSTGRES_MAXACTIVE=$POSTGRES_MAXACTIVE \
  $CATALINA_OPTS"
