kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: farms-legacy-route-#{ENV}#
  namespace: '#{NAMESPACE}#'
  labels: {}
spec:
  to:
    kind: Service
    name: farms-legacy-service-#{ENV}#
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ''
  port:
    targetPort: #{TOMCAT_PORT}#
