CREATE TABLE farms.farm_client_subscriptions (
	client_subscription_id bigint NOT NULL,
	subscription_number varchar(32) NOT NULL,
	generated_date timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	generated_by_userid varchar(30) NOT NULL,
	activated_date timestamp(0),
	activation_expiry_date timestamp(0) NOT NULL,
	agristability_represntve_id bigint,
	agristability_client_id bigint NOT NULL,
	subscription_status_code varchar(10) NOT NULL,
	revision_count integer NOT NULL DEFAULT 1,
	who_created varchar(30) NOT NULL,
	when_created timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	who_updated varchar(30),
	when_updated timestamp(0) DEFAULT statement_timestamp()
) ;
COMMENT ON TABLE farms.farm_client_subscriptions IS E'CLIENT SUBSCRIPTION relates many instances of an AGRISTABILITY CLIENT to many instances of an AGRISTABILITY REPRESENTATIVE. A subscription allows a person to represent a client. A client can represent themself. A subscription has a limited time during which it can be activated.';
COMMENT ON COLUMN farms.farm_client_subscriptions.activated_date IS E'ACTIVATED DATE identifies the date and time that the subcription was activated.';
COMMENT ON COLUMN farms.farm_client_subscriptions.activation_expiry_date IS E'ACTIVATION EXPIRY DATE identifies the date and time after which the subscription can no longer be activated.';
COMMENT ON COLUMN farms.farm_client_subscriptions.agristability_client_id IS E'AGRISTABILITY CLIENT ID is a surrogate unique identifier for AGRI STABILITY CLIENTs.';
COMMENT ON COLUMN farms.farm_client_subscriptions.agristability_represntve_id IS E'AGRISTABILITY REPRESNTVE ID is a surrogate unique identifier for AGRISTABILITY REPRESENTATIVEs.';
COMMENT ON COLUMN farms.farm_client_subscriptions.client_subscription_id IS E'CLIENT SUBSCRIPTION ID is a surrogate unique identifier for CLIENT SUBSCRIPTIONs.';
COMMENT ON COLUMN farms.farm_client_subscriptions.generated_by_userid IS E'GENERATED BY USERID indicates the user that created the suscription.';
COMMENT ON COLUMN farms.farm_client_subscriptions.generated_date IS E'GENERATED DATE identifies the date and time that the subcription was generated.';
COMMENT ON COLUMN farms.farm_client_subscriptions.revision_count IS E'REVISION COUNT is a counter identifying the number of times this record as been modified. Used in the web page access to determine if the record as been modified since the data was first retrieved.';
COMMENT ON COLUMN farms.farm_client_subscriptions.subscription_number IS E'SUBSCRIPTION NUMBER is the unique value issued to a user of the application to facilitate the user registration process.';
COMMENT ON COLUMN farms.farm_client_subscriptions.subscription_status_code IS E'SUBSCRIPTION STATUS CODE identifies the status of an AGRISTABILITY SUBSCRIPTION .  Possible Values: GEN - Generated, ACT - Activated, INV - Invalidated, EXP - Expired.';
COMMENT ON COLUMN farms.farm_client_subscriptions.when_created IS E'WHEN CREATED indicates when the physical record was created in the database.';
COMMENT ON COLUMN farms.farm_client_subscriptions.when_updated IS E'WHEN UPDATED indicates when the physical record was updated in the database.';
COMMENT ON COLUMN farms.farm_client_subscriptions.who_created IS E'WHO CREATED indicates the user that created the physical record in the database.';
COMMENT ON COLUMN farms.farm_client_subscriptions.who_updated IS E'WHO UPDATED indicates the user that updated the physical record in the database.';
CREATE INDEX farm_csub_farm_asc_fk_i ON farms.farm_client_subscriptions (agristability_client_id);
CREATE INDEX farm_csub_farm_asr_fk_i ON farms.farm_client_subscriptions (agristability_represntve_id);
CREATE INDEX farm_csub_farm_fssc_fk_i ON farms.farm_client_subscriptions (subscription_status_code);
ALTER TABLE farms.farm_client_subscriptions ADD CONSTRAINT farm_csub_pk PRIMARY KEY (client_subscription_id);
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN client_subscription_id SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN subscription_number SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN generated_date SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN generated_by_userid SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN activation_expiry_date SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN agristability_client_id SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN subscription_status_code SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN revision_count SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN who_created SET NOT NULL;
ALTER TABLE farms.farm_client_subscriptions ALTER COLUMN when_created SET NOT NULL;
