//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.11 at 03:57:20 PST
//


package ca.bc.gov.srm.farm.ui.domain.resultsimport;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the ca.bc.gov.srm.farm.ui.domain.resultsimport package. <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this class.
 *
 */
public class ObjectFactory
    extends com.sun.xml.bind.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();

    static {
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.PROGRAMYEARSType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PARTICIPANTTypeImpl.PROGRAMYEARSTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODEType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.COMMODITYCODETypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANT.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PARTICIPANTImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENTType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.AGRISTATIBLITYCLIENTTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODE.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.COMMODITYCODEImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODEType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.LINECODETypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEAR.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PROGRAMYEARImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODE.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.LINECODEImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSON.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PERSONImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PARTICIPANTSType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGTypeImpl.PARTICIPANTSTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNIT.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PRODUCTIONUNITImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENT.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.AGRISTATIBLITYCLIENTImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.ERROR.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ERRORImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOG.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PARTICIPANTTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEARType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PROGRAMYEARTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PRODUCTIONUNITSType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGTypeImpl.PRODUCTIONUNITSTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.WARNING.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.WARNINGImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTR.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ATTRImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNITType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PRODUCTIONUNITTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSONType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PERSONTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.LINECODESType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGTypeImpl.LINECODESTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTRType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ATTRTypeImpl.class));
        defaultImplementations.put((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.COMMODITIESType.class), (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGTypeImpl.COMMODITIESTypeImpl.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.srm.farm.ui.domain.resultsimport
     *
     */
    public ObjectFactory() {
        super(new ca.bc.gov.srm.farm.ui.domain.resultsimport.ObjectFactory.GrammarInfoImpl());
    }

    /**
     * Create an instance of the specified Java content interface.
     *
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param name the name of the property to retrieve
     * @param value the value of the property to be set
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of PARTICIPANTTypePROGRAMYEARSType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.PROGRAMYEARSType createPARTICIPANTTypePROGRAMYEARSType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.PROGRAMYEARSType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.PROGRAMYEARSType.class)));
    }

    /**
     * Create an instance of COMMODITYCODEType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODEType createCOMMODITYCODEType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODEType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODEType.class)));
    }

    /**
     * Create an instance of PARTICIPANT
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANT createPARTICIPANT()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANT) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANT.class)));
    }

    /**
     * Create an instance of AGRISTATIBLITYCLIENTType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENTType createAGRISTATIBLITYCLIENTType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENTType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENTType.class)));
    }

    /**
     * Create an instance of COMMODITYCODE
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODE createCOMMODITYCODE()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODE) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.COMMODITYCODE.class)));
    }

    /**
     * Create an instance of LINECODEType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODEType createLINECODEType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODEType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODEType.class)));
    }

    /**
     * Create an instance of PROGRAMYEAR
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEAR createPROGRAMYEAR()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEAR) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEAR.class)));
    }

    /**
     * Create an instance of LINECODE
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODE createLINECODE()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODE) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.LINECODE.class)));
    }

    /**
     * Create an instance of PERSON
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSON createPERSON()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSON) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSON.class)));
    }

    /**
     * Create an instance of IMPORTLOGTypePARTICIPANTSType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PARTICIPANTSType createIMPORTLOGTypePARTICIPANTSType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PARTICIPANTSType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PARTICIPANTSType.class)));
    }

    /**
     * Create an instance of PRODUCTIONUNIT
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNIT createPRODUCTIONUNIT()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNIT) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNIT.class)));
    }

    /**
     * Create an instance of IMPORTLOGType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType createIMPORTLOGType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.class)));
    }

    /**
     * Create an instance of AGRISTATIBLITYCLIENT
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENT createAGRISTATIBLITYCLIENT()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENT) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.AGRISTATIBLITYCLIENT.class)));
    }

    /**
     * Create an instance of ERROR
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.ERROR createERROR()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.ERROR) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.ERROR.class)));
    }

    /**
     * Create an instance of ERROR
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.ERROR createERROR(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ERRORImpl(value);
    }

    /**
     * Create an instance of IMPORTLOG
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOG createIMPORTLOG()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOG) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOG.class)));
    }

    /**
     * Create an instance of PARTICIPANTType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType createPARTICIPANTType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType.class)));
    }

    /**
     * Create an instance of PROGRAMYEARType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEARType createPROGRAMYEARType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEARType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PROGRAMYEARType.class)));
    }

    /**
     * Create an instance of IMPORTLOGTypePRODUCTIONUNITSType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PRODUCTIONUNITSType createIMPORTLOGTypePRODUCTIONUNITSType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PRODUCTIONUNITSType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.PRODUCTIONUNITSType.class)));
    }

    /**
     * Create an instance of WARNING
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.WARNING createWARNING()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.WARNING) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.WARNING.class)));
    }

    /**
     * Create an instance of WARNING
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.WARNING createWARNING(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.WARNINGImpl(value);
    }

    /**
     * Create an instance of ATTR
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTR createATTR()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTR) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTR.class)));
    }

    /**
     * Create an instance of PRODUCTIONUNITType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNITType createPRODUCTIONUNITType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNITType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PRODUCTIONUNITType.class)));
    }

    /**
     * Create an instance of PERSONType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSONType createPERSONType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSONType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.PERSONType.class)));
    }

    /**
     * Create an instance of IMPORTLOGTypeLINECODESType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.LINECODESType createIMPORTLOGTypeLINECODESType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.LINECODESType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.LINECODESType.class)));
    }

    /**
     * Create an instance of ATTRType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTRType createATTRType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTRType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.ATTRType.class)));
    }

    /**
     * Create an instance of IMPORTLOGTypeCOMMODITIESType
     *
     * @throws JAXBException if an error occurs
     */
    public ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.COMMODITIESType createIMPORTLOGTypeCOMMODITIESType()
        throws javax.xml.bind.JAXBException
    {
        return ((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.COMMODITIESType) newInstance((ca.bc.gov.srm.farm.ui.domain.resultsimport.IMPORTLOGType.COMMODITIESType.class)));
    }

    private static class GrammarInfoImpl
        extends com.sun.xml.bind.GrammarInfo
    {


        public java.lang.Class getDefaultImplementation(java.lang.Class javaContentInterface) {
            return ((java.lang.Class) defaultImplementations.get(javaContentInterface));
        }

        public java.lang.Class getRootElement(java.lang.String uri, java.lang.String local) {
            if (("" == uri)&&("PARTICIPANT" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PARTICIPANTImpl.class);
            }
            if (("" == uri)&&("WARNING" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.WARNINGImpl.class);
            }
            if (("" == uri)&&("ERROR" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ERRORImpl.class);
            }
            if (("" == uri)&&("PERSON" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PERSONImpl.class);
            }
            if (("" == uri)&&("IMPORT_LOG" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.IMPORTLOGImpl.class);
            }
            if (("" == uri)&&("PROGRAM_YEAR" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PROGRAMYEARImpl.class);
            }
            if (("" == uri)&&("PRODUCTION_UNIT" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.PRODUCTIONUNITImpl.class);
            }
            if (("" == uri)&&("COMMODITYCODE" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.COMMODITYCODEImpl.class);
            }
            if (("" == uri)&&("AGRISTATIBLITY_CLIENT" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.AGRISTATIBLITYCLIENTImpl.class);
            }
            if (("" == uri)&&("LINECODE" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.LINECODEImpl.class);
            }
            if (("" == uri)&&("ATTR" == local)) {
                return (ca.bc.gov.srm.farm.ui.domain.resultsimport.impl.ATTRImpl.class);
            }
            return null;
        }

        public java.lang.String[] getProbePoints() {
            return new java.lang.String[] {"", "PARTICIPANT", "", "WARNING", "", "ERROR", "", "PERSON", "", "IMPORT_LOG", "", "PROGRAM_YEAR", "", "PRODUCTION_UNIT", "", "COMMODITYCODE", "", "AGRISTATIBLITY_CLIENT", "", "LINECODE", "", "ATTR"};
        }

    }

}
