//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.11 at 03:57:20 PST
//


package ca.bc.gov.srm.farm.ui.domain.resultsimport;


/**
 * Java content class for PARTICIPANT element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="PARTICIPANT">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}AGRISTATIBLITY_CLIENT"/>
 *           &lt;element name="PROGRAM_YEARS" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{}PROGRAM_YEAR" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;attribute name="altered" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="last_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="first_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="pin" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *         &lt;attribute name="corp_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 */
public interface PARTICIPANT
    extends javax.xml.bind.Element, ca.bc.gov.srm.farm.ui.domain.resultsimport.PARTICIPANTType
{


}
