//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.11 at 03:57:20 PST
//


package ca.bc.gov.srm.farm.ui.domain.resultsimport;


/**
 * Java content class for annonymous complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ERROR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}WARNING" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="altered" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="year" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="action" use="required" type="{}action_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface PROGRAMYEARType {


    java.math.BigInteger getYear();

    void setYear(java.math.BigInteger value);

    java.lang.String getAction();

    void setAction(java.lang.String value);

    java.util.List getERROR();

    java.lang.String getAltered();

    void setAltered(java.lang.String value);

    java.util.List getWARNING();

    int getNumberOfErrors();

    int getNumberOfWarnings();

}
