//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.11 at 03:57:20 PST
//


package ca.bc.gov.srm.farm.ui.domain.resultsimport;


/**
 * Java content class for WARNING element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="WARNING" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * </pre>
 *
 */
public interface WARNING
    extends javax.xml.bind.Element
{


    java.lang.String getValue();

    void setValue(java.lang.String value);

}
