spring:
  application:
    name: farms-api

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ca.bc.gov.farms.data.entities
  configuration:
    map-underscore-to-camel-case: true
