name: Build .war files

on:
  workflow_dispatch:
    inputs:
      TAG:
          required: true
          type: string
          description: Additional tag to apply to images being built
          default: latest

jobs:
  

  build-farms-api:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      TAG: ${{ inputs.tag }}
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: farms-api
      JAVA_VERSION: 21
