name: farms-api CI build

on:
  pull_request_target:
    branches:
      - main
    paths:
      - farms-api/**

jobs:
  build-farms-api:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      TAG: 1.0.0
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: farms-api
      JAVA_VERSION: 17
      DEPLOYMENT_BRANCH: ${{ github.event.pull_request.head.ref }}

  openshift-deploy:
    needs: build-farms-api
    uses: ./.github/workflows/openshift-deploy.yml
    secrets: inherit
    with:
      TAG: 1.0.0
      MICROSERVICE_NAME: farms-api
      NAMESPACE: e980f4-dev
      ENVIRONMENT_NAME: dev


