name: load test
run-name: Load test ${{ inputs.MICROSERVICE_NAME }}

on:
  workflow_dispatch:
    inputs:
      MICROSERVICE_NAME:
        required: true
        type: choice
        options:
          - farms-api
      ENVIRONMENT_NAME:
        required: true
        type: choice
        options:
          - dev
          - dlvr
          - test
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install JMeter
        run: |
          wget -O apache-jmeter.tgz https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter.tgz

      - name: Run JMeter
        run: |
          apache-jmeter/bin/jmeter \
            -n \
            -t load-tests/${{ inputs.MICROSERVICE_NAME }}-load-test.jmx \
            -Jtenant_id=${{ secrets.TENANT_ID }} \
            -Jclient_id=${{ secrets.CLIENT_ID }} \
            -Jclient_secret=${{ secrets.CLIENT_SECRET }} \
            -Jhost=${{ vars.API_HOST }} \
            -Jthreads=1 \
            -l results.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
          if-no-files-found: error
