name: load test
run-name: Load test ${{ inputs.MICROSERVICE_NAME }}

on:
  workflow_dispatch:
    inputs:
      MICROSERVICE_NAME:
        required: true
        type: choice
        options:
          - farms-api
      ENVIRONMENT_NAME:
        required: true
        type: choice
        options:
          - dev
          - dlvr
          - test
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./load-tests/${{ inputs.MICROSERVICE_NAME }}-load-test.jmx
          args: "-Jtenant_id=${{ secrets.TENANT_ID }} -Jclient_id=${{ secrets.CLIENT_ID }} -Jclient_secret=${{ secrets.CLIENT_SECRET }} -Jhost=${{ vars.API_HOST }} -Jthreads=1"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error
