CREATE TABLE farms.farm_client_subscriptions(
    client_subscription_id             numeric(10, 0)    NOT NULL,
    subscription_number                varchar(32)       NOT NULL,
    generated_date                     date              DEFAULT CURRENT_TIMESTAMP NOT NULL,
    generated_by_userid                varchar(30)       NOT NULL,
    activated_date                     date,
    activation_expiry_date             date              NOT NULL,
    agristability_represntve_id    numeric(10, 0),
    agristability_client_id            numeric(10, 0)    NOT NULL,
    subscription_status_code           varchar(10)       NOT NULL,
    revision_count                     numeric(5, 0)     DEFAULT 1 NOT NULL,
    who_created                        varchar(30)       NOT NULL,
    when_created                        timestamp(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    who_updated                        varchar(30),
    when_updated                        timestamp(6)      DEFAULT CURRENT_TIMESTAMP
) TABLESPACE pg_default
;



COMMENT ON COLUMN farms.farm_client_subscriptions.client_subscription_id IS 'CLIENT SUBSCRIPTION ID is a surrogate unique identifier for CLIENT SUBSCRIPTIONs.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.subscription_number IS 'SUBSCRIPTION NUMBER is the unique value issued to a user of the application to facilitate the user registration process.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.generated_date IS 'GENERATED DATE identifies the date and time that the subscription was generated.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.generated_by_userid IS 'GENERATED BY USERID indicates the user that created the subscription.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.activated_date IS 'ACTIVATED DATE identifies the date and time that the subscription was activated.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.activation_expiry_date IS 'ACTIVATION EXPIRY DATE identifies the date and time after which the subscription can no longer be activated.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.agristability_represntve_id IS 'AGRISTABILITY REPRESENTATIVE ID is a surrogate unique identifier for AGRISTABILITY REPRESENTATIVEs.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.agristability_client_id IS 'AGRISTABILITY CLIENT ID is a surrogate unique identifier for AGRI STABILITY CLIENTs.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.subscription_status_code IS 'SUBSCRIPTION STATUS CODE identifies the status of an AGRISTABILITY SUBSCRIPTION .  Possible Values: GEN - Generated, ACT - Activated, INV - Invalidated, EXP - Expired.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.revision_count IS 'REVISION COUNT is a counter identifying the number of times this record as been modified. Used in the web page access to determine if the record as been modified since the data was first retrieved.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.who_created IS 'CREATE USER indicates the user that created the physical record in the database.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.when_created IS 'CREATE DATE indicates when the physical record was created in the database.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.who_updated IS 'UPDATE USER indicates the user that updated the physical record in the database.'
;
COMMENT ON COLUMN farms.farm_client_subscriptions.when_updated IS 'UPDATE DATE indicates when the physical record was updated in the database.'
;
COMMENT ON TABLE farms.farm_client_subscriptions IS 'CLIENT SUBSCRIPTION relates many instances of an AGRISTABILITY CLIENT to many instances of an AGRISTABILITY REPRESENTATIVE. A subscription allows a person to represent a client. A client can represent themself. A subscription has a limited time during which it can be activated.'
;


CREATE INDEX ix_cs1_aci ON farms.farm_client_subscriptions(agristability_client_id)
 TABLESPACE pg_default
;
CREATE INDEX ix_cs1_ari ON farms.farm_client_subscriptions(agristability_represntve_id)
 TABLESPACE pg_default
;
CREATE INDEX ix_cs1_ssc ON farms.farm_client_subscriptions(subscription_status_code)
 TABLESPACE pg_default
;

ALTER TABLE farms.farm_client_subscriptions ADD 
    CONSTRAINT pk_cs1 PRIMARY KEY (client_subscription_id) USING INDEX TABLESPACE pg_default 
;
